In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

<font size=5, color='red'>ch03. 연관분석</font>
- pip install apyori
# 1. 연관 분석 개요
- 데이터들 사이에 자주 발생하는 속성을 찾고 그 속성들 사이에 연관성이 어느 정도 있는 지 분석
- 활용분야 : 이벤트 미리 감지(사기 적발..), 신상품 카테고리 구성
- 용어사전
    예시와 함께 설명, 보조자료 'data/cf_basket.csv' 체크
    [조건 : left hand side as lhs] 오렌지주스 => [결과 : right hand side as rhs] 와인
    - 연관분석과 관련된 지표
    1. 지지도(support) : 얼마나 자주 함께 나타나는 지
        (lhs와 rhs)의 항목수 / 전체 항목수 = 0.2
        
    2. 신뢰도(confidence) : 조건이 오면 결과가 얼마나 자주 나타나는 지
        (lhs -> rhs)의 항목수 / lhs가 포함된 항목수 = 0.5
        
    3. 향상도(lift) : 우연히 발생한 규칙은 아닌 지 확인
        (lhs -> rhs)의 지지도 / (lhs의 지지도) * (rhs의 지지도)
            => 0.2 / (0.4 * 0.6) = 0.2 / 0.24 =0.8333...
            향상도 < 1 기대가 낮음(없음)
            향상도 > 1 기대가 높음(있음)

# 2. 연관 분석 구현

In [7]:
import csv
transaction = []
with open('data/cf_basket.csv','r',encoding='utf-8') as f :
    csvdata = csv.reader(f)
    transaction = list(csvdata)
transaction

[['소주', '콜라', '와인'],
 ['소주', '오렌지주스', '콜라'],
 ['맥주', '콜라', '와인'],
 ['소주', '콜라', '맥주'],
 ['오렌지주스', '와인']]

In [12]:
from apyori import apriori
rules = apriori(transaction, # 2차원 데이터
                min_support = 0.15,
               min_confidence = 0.1,
               ) # 매개변수 : min_support min_confidence min_lift max_length 
# len(list(rules)) # 18개 규칙이 생성
rules = list(rules)

In [54]:
rules[10][2]

[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'소주', '콜라'}), confidence=0.6, lift=1.0),
 OrderedStatistic(items_base=frozenset({'소주'}), items_add=frozenset({'콜라'}), confidence=1.0, lift=1.25),
 OrderedStatistic(items_base=frozenset({'콜라'}), items_add=frozenset({'소주'}), confidence=0.7499999999999999, lift=1.2499999999999998)]

In [46]:
rule = rules[10]
support = rule[1]
order_st = rule[2]
print('{LHS}\t\t => \t\t{RHS}\t     {support} {confidence} {lift}')
for item in order_st :
    lhs = item[0]
    rhs = item[1]
    confidence = item[2]
    lift = item[3]
    if lift > 1 :
        print('{} => {}\t {:.2f} \t  {:.2f} \t     {:.2f}'.format(lhs, rhs, support, confidence, lift))

{LHS}		 => 		{RHS}	     {support} {confidence} {lift}
frozenset({'소주'}) => frozenset({'콜라'})	 0.60 	  1.00 	     1.25
frozenset({'콜라'}) => frozenset({'소주'})	 0.60 	  0.75 	     1.25

In [47]:
for rule in rules :
    support = rule[1]
    order_st = rule[2]
    
    for item in order_st :
        lhs = item[0]
        rhs = item[1]
        confidence = item[2]
        lift = item[3]
        if lift > 1 :
            print('{} => {}\t {:.2f} \t  {:.2f} \t     {:.2f}'.format(lhs, rhs, support, confidence, lift))

frozenset({'맥주'}) => frozenset({'콜라'})	 0.40 	  1.00 	     1.25
frozenset({'콜라'}) => frozenset({'맥주'})	 0.40 	  0.50 	     1.25
frozenset({'소주'}) => frozenset({'콜라'})	 0.60 	  1.00 	     1.25
frozenset({'콜라'}) => frozenset({'소주'})	 0.60 	  0.75 	     1.25
frozenset({'콜라'}) => frozenset({'소주', '맥주'})	 0.20 	  0.25 	     1.25
frozenset({'소주', '맥주'}) => frozenset({'콜라'})	 0.20 	  1.00 	     1.25
frozenset({'맥주'}) => frozenset({'콜라', '와인'})	 0.20 	  0.50 	     1.25
frozenset({'콜라'}) => frozenset({'맥주', '와인'})	 0.20 	  0.25 	     1.25
frozenset({'와인', '맥주'}) => frozenset({'콜라'})	 0.20 	  1.00 	     1.25
frozenset({'콜라', '와인'}) => frozenset({'맥주'})	 0.20 	  0.50 	     1.25
frozenset({'소주'}) => frozenset({'콜라', '오렌지주스'})	 0.20 	  0.33 	     1.67
frozenset({'콜라'}) => frozenset({'소주', '오렌지주스'})	 0.20 	  0.25 	     1.25
frozenset({'소주', '오렌지주스'}) => frozenset({'콜라'})	 0.20 	  1.00 	     1.25
frozenset({'콜라', '오렌지주스'}) => frozenset({'소주'})	 0.20 	  1.00 	     1.67
frozenset({'콜라'}) => frozenset({'소주', '와인'})	 0.20 	  0.25 	     1.25
frozenset({'소주', '와인'}) => frozenset({'콜라'})	 0.20 	  1.00 	     1.25

In [66]:
import pandas as pd
rules_df = pd.DataFrame(None, columns=['lhs','rhs','지지도','신뢰도','향상도'])
# rules_df.loc[0] = ['와인','오렌지',0.15,0.5,1.11]
i = 0
for rule in rules :
    support = rule[1]
    order_st = rule[2]
    
    for item in order_st :
        lhs = [i for i in item[0]]
        rhs = [i for i in item[1]]
        confidence = item[2]
        lift = item[3]
        if lift > 1 :
            rules_df.loc[i] = [' '.join(lhs),' '.join(rhs),support,confidence,lift]
            i +=1
rules_df.sort_values(by=['향상도','신뢰도'], ascending=False)

         lhs       rhs  지지도       신뢰도       향상도
13  콜라 오렌지주스        소주  0.2  1.000000  1.666667
10        소주  콜라 오렌지주스  0.2  0.333333  1.666667
0         맥주        콜라  0.4  1.000000  1.250000
2         소주        콜라  0.6  1.000000  1.250000
5      소주 맥주        콜라  0.2  1.000000  1.250000
8      와인 맥주        콜라  0.2  1.000000  1.250000
12  소주 오렌지주스        콜라  0.2  1.000000  1.250000
15     소주 와인        콜라  0.2  1.000000  1.250000
1         콜라        맥주  0.4  0.500000  1.250000
6         맥주     콜라 와인  0.2  0.500000  1.250000
9      콜라 와인        맥주  0.2  0.500000  1.250000
4         콜라     소주 맥주  0.2  0.250000  1.250000
7         콜라     맥주 와인  0.2  0.250000  1.250000
11        콜라  소주 오렌지주스  0.2  0.250000  1.250000
14        콜라     소주 와인  0.2  0.250000  1.250000
3         콜라        소주  0.6  0.750000  1.250000

# 3. 경주/전주 여행 자료 연관 분석

In [77]:
df = pd.read_csv('data/naver_kin.csv', sep = '\t')
total_text_list = df['total_text'].tolist()

In [91]:
%%time
# 이 셀은 실행시킬 때 시간 오래 걸리니까 주의
from konlpy.tag import Hannanum, Kkma
hannanum = Kkma()
total_noun_list = []
select_pos = {'NC','NQ', 'NNP','NNG'}
불용어 = {'여행', '전주여행', '경주여행'}
for text in total_text_list :
    temp=[word for word, tag in hannanum.pos(text) if tag in select_pos and word not in 불용어 and len(word) > 1 ]# 보통명사, 고유명사만 추출
    total_noun_list.append(temp)

In [92]:
total_noun_list

[['전주',
  '추천',
  '추억',
  '다양',
  '체험',
  '추억',
  '테마',
  '박물관',
  '유익',
  '시간',
  '투어',
  '패스',
  '통합',
  '이용권',
  '여행지',
  '다양',
  '체험',
  '카페',
  '이용',
  '추가',
  '전주',
  '필수',
  '편안',
  '감사'],
 ['전주',
  '전주',
  '사람',
  '호텔',
  '가격',
  '얼마',
  '정도',
  '카페',
  '추천',
  '주세',
  '안녕',
  '하세',
  '전주',
  '계획',
  '중이',
  '한옥',
  '마을',
  '근처'],
 ['전주',
  '관련',
  '질문',
  '전주',
  '계획',
  '선택',
  '전주',
  '한옥',
  '마을',
  '자연',
  '경관',
  '음식',
  '동네',
  '시간',
  '한옥',
  '마을',
  '근처',
  '장소'],
 ['학생', '친구', '전주', '안녕', '하세', '여학생', '친구', '전주', '가기', '일본', '전주', '오타쿠'],
 ['모닝',
  '전주',
  '부모님',
  '전주',
  '명소',
  '식당',
  '추천',
  '전주',
  '한옥',
  '마을',
  '유명',
  '완산구',
  '덕진구',
  '추억',
  '장소'],
 ['전주',
  '이번',
  '여자',
  '친구',
  '전주',
  '경로',
  '주세',
  '토요일',
  '실내',
  '데이트',
  '가능',
  '감사',
  '숙소',
  '전주',
  '한옥',
  '마을',
  '근처',
  '한옥',
  '마을',
  '구경'],
 ['전주',
  '저녁',
  '전주',
  '산책길',
  '한옥',
  '마을',
  '근처',
  '야경',
  '일정',
  '관심',
  '테마',
  '사진',
  '카페',
  '체험',
  '맞춤',
  '추천',
  '전주'],
 ['전주',
  '코스',
  '추천',
  '이요',
  '영화제',
  '기간',
  '일정',
  '전주',
  '코스',
  '추천',
  '목적',
  '전주',
  '국제',
  '영화',
  '전주',
  '알짜',
  '배기',
  '추천',
  '주세',
  '전주'],
 ['전주',
  '전주',
  '커플',
  '추천',
  '주세',
  '숙소',
  '거리',
  '추천',
  '감사',
  '한옥',
  '마을',
  '변이',
  '도움',
  '한옥',
  '마을',
  '전주',
  '한옥',
  '마을',
  '전주',
  '전주',
  '거리',
  '전주',
  '추천'],
 ['추석',
  '전주',
  '전주',
  '그때',
  '한옥',
  '마을',
  '관광지',
  '추석',
  '당일',
  '전주',
  '이벤트',
  '진행',
  '한국',
  '관광',
  '공사',
  '숙박',
  '세일',
  '스타',
  '이벤트',
  '진행'],
 ['전주',
  '연령',
  '렌트카',
  '추천',
  '이번',
  '전주',
  '전주',
  '연령',
  '자동차',
  '추천',
  '가격',
  '렌트',
  '정도',
  '전주',
  '이상',
  '렌트',
  '가능',
  '자동차',
  '가격'],
 ['전주',
  '포항',
  '전주',
  '포항',
  '기차',
  '버스',
  '안녕',
  '하세',
  '전주',
  '포항',
  '기차',
  '버스',
  '장단점',
  '방법',
  '결정',
  '요소',
  '고려',
  '필요'],
 ['전주',
  '한옥',
  '이요',
  '이번',
  '남자',
  '친구',
  '전주',
  '가기',
  '전주',
  '한옥',
  '마을',
  '근처',
  '한옥',
  '느낌',
  '전주',
  '내부',
  '정감',
  '분위기',
  '답변',
  '부탁'],
 ['전주', '주세', '전주', '한옥', '마을', '유명', '완산구', '덕진구', '추억', '장소', '완산구', '덕진구'],
 ['전주',
  '엄마',
  '전주',
  '계획',
  '답변',
  '부탁',
  '기차',
  '고속버스',
  '전주',
  '도착',
  '관광',
  '이용',
  '교통수단',
  '추천',
  '서울'],
 ['전주',
  '당일',
  '전주',
  '당일',
  '계획',
  '중이',
  '전주',
  '한옥',
  '마을',
  '방법',
  '당일',
  '코스',
  '전주',
  '한옥',
  '마을',
  '방법',
  '택시',
  '버스',
  '전주',
  '한옥',
  '마을',
  '택시'],
 ['전주',
  '경비',
  '보통',
  '전주',
  '경비',
  '얼마',
  '정도',
  '숙소',
  '질문',
  '도움',
  '답변',
  '전주',
  '예산',
  '내외',
  '숙소'],
 ['전주',
  '커플',
  '전주',
  '도움',
  '남자',
  '친구',
  '이용',
  '이용',
  '요소',
  '고려',
  '만약',
  '교통',
  '체증',
  '예상',
  '날짜',
  '이용',
  '남자',
  '친구'],
 ['남해',
  '전주',
  '남해',
  '전주',
  '여행지',
  '추천',
  '주세',
  '보리',
  '다랭이',
  '독일',
  '마을',
  '전주',
  '한옥',
  '마을',
  '추천',
  '주세',
  '추천',
  '전주',
  '전주'],
 ['전주',
  '추천',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을'],
 ['전주',
  '코스',
  '질문',
  '코스',
  '주실',
  '전라도',
  '간적',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서'],
 ['전주',
  '전주',
  '비용',
  '얼마',
  '전주',
  '비용',
  '요소',
  '일반적',
  '다음',
  '항목',
  '포함',
  '교통',
  '전주',
  '이동',
  '교통',
  '비용'],
 ['전주',
  '코스',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을',
  '시작'],
 ['전주',
  '당일',
  '혼자',
  '코스',
  '추천',
  '박물관',
  '미술관',
  '지역',
  '공간',
  '스토리',
  '안내',
  '해설',
  '문화',
  '코스',
  '방지',
  '예약금',
  '결제',
  '현장',
  '상당',
  '음료',
  '환급',
  '선착순',
  '마감',
  '전주',
  '계획'],
 ['전주',
  '필요',
  '가요',
  '안녕',
  '전주',
  '계획',
  '서울',
  '전주',
  '기차',
  '전주',
  '렌트',
  '참고',
  '전주',
  '한옥',
  '마을',
  '포함',
  '유명',
  '관광지',
  '계획',
  '전주',
  '전주',
  '국내'],
 ['전주',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '대중교통',
  '택시',
  '이용'],
 ['전주',
  '완주',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '완주'],
 ['전주',
  '부탁',
  '드립',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스'],
 ['전주',
  '코스',
  '전주',
  '코스',
  '전주',
  '역사적',
  '유적지',
  '전통문화',
  '유명',
  '전주',
  '한옥',
  '마을',
  '방문',
  '한옥',
  '아름다움',
  '시작',
  '지라',
  '전주',
  '한옥',
  '마을'],
 ['전주',
  '대중교통',
  '렌트카',
  '전주',
  '차가',
  '대중교통',
  '주세',
  '교통',
  '상황',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도'],
 ['전주',
  '전주',
  '전주',
  '연인',
  '추천',
  '주한',
  '마을',
  '전주',
  '동물원',
  '한국',
  '도로',
  '공사',
  '수목원',
  '전주',
  '향교',
  '공원'],
 ['전주',
  '관련',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '주말',
  '평일',
  '인지'],
 ['전주',
  '추천',
  '주세',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달'],
 ['전주',
  '이번',
  '전주',
  '처음',
  '추천',
  '주세',
  '걷기',
  '위주',
  '트레킹',
  '전주',
  '계획',
  '중이',
  '전주',
  '다양',
  '볼거리'],
 ['전주',
  '경비',
  '식비',
  '교통비',
  '감이',
  '술값',
  '한번',
  '만원',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만'],
 ['전주',
  '비용',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '한옥',
  '마을',
  '입장료',
  '기본'],
 ['친구',
  '전주',
  '친구',
  '전주',
  '호텔',
  '추천',
  '호텔',
  '시설',
  '한옥',
  '침대',
  '양식',
  '중식',
  '일식',
  '용도'],
 ['전주',
  '크리스마스',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을',
  '시작'],
 ['전주',
  '질문',
  '전주',
  '일정',
  '관련',
  '답변',
  '여행가',
  '계획',
  '제가',
  '전주',
  '준비',
  '아래',
  '일정'],
 ['초등',
  '학년',
  '전주',
  '일대',
  '수학',
  '코스',
  '전주',
  '관광',
  '달인',
  '주달',
  '코스',
  '추천',
  '감사',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도'],
 ['전주',
  '혼자',
  '코스',
  '질문',
  '전주',
  '정보',
  '정리',
  '참고',
  '주세',
  '전주',
  '공원',
  '추천',
  '공원',
  '전주',
  '터미널',
  '산책',
  '호수',
  '공원',
  '공원',
  '생략',
  '남부',
  '시장'],
 ['전주',
  '전시회',
  '추천',
  '제가',
  '이번',
  '남자',
  '친구',
  '전주',
  '전주',
  '한옥',
  '마을',
  '가기',
  '공방',
  '전시회',
  '있음',
  '추천',
  '안녕',
  '하세',
  '질문',
  '전주',
  '관련',
  '답변',
  '가시나'],
 ['전주',
  '코스',
  '추천',
  '안녕',
  '여자',
  '친구',
  '전주',
  '예정',
  '숙소',
  '전주',
  '클래식',
  '호텔',
  '잡고',
  '일정',
  '금요일',
  '오후',
  '전주',
  '도착',
  '예정',
  '자가',
  '이동',
  '수단',
  '대중교통',
  '택시',
  '예정'],
 ['전주',
  '각각',
  '거리',
  '추석',
  '예정',
  '추천',
  '주세',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도'],
 ['전주',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을'],
 ['전주',
  '코스',
  '전주',
  '일정',
  '질문자',
  '모두',
  '반양',
  '시간',
  '무리',
  '일정',
  '일차',
  '가운데',
  '점심',
  '전주',
  '한지',
  '박물관',
  '관광',
  '전주',
  '수목원',
  '관광',
  '관광',
  '교동'],
 ['전주',
  '추천',
  '부탁',
  '전주',
  '추천',
  '부탁',
  '드립',
  '감사',
  '전주',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '언서',
  '주달',
  '전주'],
 ['강아지',
  '전주',
  '가능',
  '전주',
  '강아지',
  '동반',
  '강아지',
  '관광',
  '반려',
  '동물',
  '반려',
  '생활',
  '하늘',
  '가을',
  '전주',
  '아지',
  '추억'],
 ['광주',
  '전주',
  '감사',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '버스',
  '터미널'],
 ['전주',
  '코스',
  '주세',
  '질문',
  '전주',
  '일정',
  '관련',
  '답변',
  '어머니',
  '듣기',
  '아래',
  '일정',
  '준비',
  '참고',
  '도움'],
 ['추천',
  '주세',
  '전주',
  '당일',
  '추천',
  '주세',
  '전주',
  '당일',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달'],
 ['전주',
  '전주',
  '가기',
  '주세',
  '안녕',
  '서울',
  '지방',
  '변호',
  '사회',
  '소속',
  '지식',
  '법률',
  '상담',
  '선용',
  '변호사',
  '스타',
  '전주',
  '검색'],
 ['전주',
  '한옥',
  '마을',
  '준비',
  '천차만별',
  '기본',
  '금액',
  '시간',
  '한복',
  '가격',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도'],
 ['고등학교',
  '친구',
  '전주',
  '당일',
  '지금',
  '고등학교',
  '학년',
  '친구',
  '전주',
  '당일',
  '예정',
  '부모님',
  '허락',
  '고등',
  '학교',
  '시절',
  '친구',
  '과의',
  '추억',
  '전주',
  '전주'],
 ['전주',
  '휴가',
  '코스',
  '추천',
  '주세',
  '위의',
  '일정',
  '참고',
  '제시',
  '일정',
  '조정',
  '음식점',
  '웨이팅',
  '시간',
  '방문',
  '시간',
  '요일',
  '주세',
  '전주'],
 ['여자',
  '전주',
  '질문',
  '전주',
  '다음',
  '일정',
  '추천',
  '전주',
  '한옥',
  '마을',
  '전통',
  '한옥',
  '건물',
  '전통',
  '문화',
  '경험',
  '전주',
  '향교',
  '조선',
  '시대',
  '교육',
  '기관',
  '향교',
  '전주',
  '남부',
  '시장',
  '전주'],
 ['전주',
  '코스',
  '가족',
  '전주',
  '당장',
  '이번',
  '금요일',
  '숙소',
  '호텔',
  '한옥',
  '마을',
  '카페',
  '투어',
  '코스'],
 ['전주',
  '대둔산',
  '케이블카',
  '주말',
  '사람',
  '코스',
  '추천',
  '주세',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문'],
 ['전주', '코스', '전주', '복귀', '지난주', '당일', '코스', '전주', '주말', '관광지', '사람', '생각'],
 ['전주',
  '한옥',
  '마을',
  '당일',
  '질문',
  '전주',
  '여수',
  '제주도',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '시랑',
  '전망',
  '달곰'],
 ['전주',
  '혼자',
  '사람',
  '혼자',
  '중순',
  '전주',
  '계절',
  '현재',
  '코로나',
  '여행객',
  '사람',
  '예상',
  '전주',
  '집이'],
 ['전주',
  '제가',
  '이번',
  '친구',
  '전주',
  '답장',
  '감사',
  '여수',
  '전주',
  '왕복',
  '기차표',
  '얼마',
  '전주'],
 ['전주',
  '월요일',
  '휴무',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '걱정',
  '대부분',
  '오픈'],
 ['내일',
  '전주',
  '당일',
  '부모님',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '바다',
  '군산'],
 ['전주',
  '숙소',
  '한옥',
  '마을',
  '게스트',
  '하우스',
  '안녕',
  '가족',
  '전주',
  '한옥',
  '마을',
  '유명',
  '전주',
  '한번',
  '이번',
  '기회',
  '전라도',
  '음식',
  '전주',
  '전라도',
  '대표',
  '음식',
  '집도'],
 ['전주',
  '코스',
  '추천',
  '전주',
  '코스',
  '추천',
  '전주',
  '여수',
  '전주',
  '여수',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '언서',
  '주달',
  '전주',
  '코스',
  '대부분',
  '한옥',
  '마을',
  '시작'],
 ['전주',
  '볼거리',
  '이번',
  '전주',
  '볼거리',
  '주세',
  '전주',
  '추천',
  '주한',
  '마을',
  '전주',
  '동물원',
  '한국',
  '도로',
  '공사',
  '수목원',
  '공원',
  '전주',
  '난장'],
 ['전주',
  '오션',
  '카페',
  '추천',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '바다'],
 ['전주',
  '가족',
  '코스',
  '문의',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을'],
 ['전주',
  '코스',
  '일정',
  '추천',
  '토요일',
  '하루',
  '일정',
  '수정',
  '필요',
  '부분',
  '인근',
  '의견',
  '부탁',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도'],
 ['전주', '전주', '한옥', '마을', '근처', '숙박', '버스', '택시', '조금', '가도', '추천'],
 ['전주',
  '코스',
  '아침',
  '전주',
  '현대',
  '본점',
  '점심',
  '전주',
  '비빔',
  '소리',
  '현대',
  '비빔',
  '소리',
  '중간',
  '구경',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스'],
 ['전라도', '전주', '전주', '한번', '예정', '추천', '체험', '전주', '추천', '전주', '한옥', '마을'],
 ['전주',
  '참고',
  '전주',
  '계획',
  '중이',
  '전주',
  '추천',
  '한국',
  '도로',
  '공사',
  '수목원',
  '전주',
  '동물원',
  '자만',
  '마을',
  '벽화',
  '갤러리',
  '국립',
  '전주',
  '박물관'],
 ['전주',
  '코스',
  '추천',
  '전주',
  '코스',
  '추천',
  '안녕',
  '하세',
  '전주',
  '전주',
  '로그',
  '주달',
  '대부분',
  '코스',
  '전주',
  '한옥',
  '마을',
  '경기',
  '남부',
  '시장',
  '야시장',
  '벽화',
  '마을',
  '전동',
  '성당',
  '향교',
  '추가'],
 ['전주',
  '코스',
  '동선',
  '주세',
  '숙소',
  '완산구',
  '신동',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '한옥',
  '마을'],
 ['전주',
  '크리스마스',
  '단둘',
  '당일',
  '전주',
  '고등',
  '학생',
  '정도',
  '전주',
  '답변',
  '대학로',
  '투어',
  '공연',
  '연극',
  '추천'],
 ['제가',
  '전주',
  '제가',
  '전라도',
  '사투리',
  '양이',
  '듣기',
  '거북',
  '전주',
  '인진',
  '사람',
  '라도',
  '사투리',
  '의외',
  '전라',
  '북도',
  '전주시'],
 ['전주',
  '코스',
  '추천',
  '조언',
  '주세',
  '전주',
  '한옥',
  '마을',
  '경기',
  '전주',
  '난장',
  '전주',
  '국립',
  '박물관',
  '전주',
  '동물원',
  '이동',
  '수단',
  '자동차',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도'],
 ['전주',
  '한옥',
  '마을',
  '근처',
  '이용',
  '장소',
  '장소',
  '운송',
  '가능',
  '가격',
  '실시간',
  '주문',
  '현황',
  '확인',
  '가능',
  '편리',
  '이용',
  '가능',
  '전주',
  '참고',
  '전주'],
 ['전주',
  '일정',
  '이번',
  '전주',
  '소요',
  '시간',
  '한옥',
  '마을',
  '파이',
  '체험',
  '수목원',
  '드림',
  '랜드',
  '이동',
  '시간',
  '전주',
  '한옥',
  '마을',
  '파이',
  '체험'],
 ['이번',
  '태교',
  '강아지',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '숙소',
  '잡기',
  '바닷가'],
 ['전주',
  '추천',
  '주세',
  '전주',
  '추천',
  '주세',
  '주식',
  '문화',
  '전일',
  '슈퍼',
  '전주',
  '문화',
  '평점',
  '주식',
  '정식',
  '최고',
  '수구',
  '전라',
  '회관',
  '전주',
  '비빔밥',
  '최고',
  '고궁',
  '성미',
  '토종',
  '명품',
  '사용',
  '요리'],
 ['전주',
  '혼자',
  '코스',
  '질문',
  '전주',
  '정보',
  '정리',
  '참고',
  '주세',
  '전주',
  '공원',
  '추천',
  '공원',
  '전주',
  '터미널',
  '산책',
  '호수',
  '공원',
  '공원',
  '생략',
  '남부',
  '시장'],
 ['전주',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을',
  '시작'],
 ['전주',
  '부모님',
  '전주',
  '정보',
  '하나',
  '숙소',
  '관광지',
  '추천',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수'],
 ['전주', '코스', '전주', '복귀', '지난주', '당일', '코스', '전주', '주말', '관광지', '사람', '생각'],
 ['전주',
  '당일',
  '질문',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '기지',
  '산책',
  '저녁'],
 ['전주',
  '코스',
  '추천',
  '남자',
  '친구',
  '생일',
  '전주',
  '전주',
  '처음',
  '코스',
  '추천',
  '부탁',
  '드립',
  '숙소',
  '전주',
  '한옥',
  '마을',
  '도보',
  '거리',
  '자차',
  '이동',
  '집도',
  '추천'],
 ['전주',
  '한옥',
  '마을',
  '혼자',
  '예정',
  '욕조',
  '무리',
  '질문',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서'],
 ['전주',
  '렌트',
  '전주',
  '렌트',
  '반려',
  '애견',
  '동반',
  '플랫폼',
  '하트',
  '전주',
  '도시',
  '택시',
  '이동',
  '불편',
  '변이',
  '도움',
  '채택',
  '부탁'],
 ['전주',
  '코스',
  '질문',
  '이상은',
  '제가',
  '전주',
  '문의',
  '통상',
  '안내',
  '정보',
  '질문',
  '요약',
  '사이트',
  '예약',
  '오전'],
 ['전주',
  '코스',
  '질문',
  '내공',
  '부산',
  '전주',
  '자차',
  '버스',
  '위주',
  '전주',
  '전주',
  '전주',
  '버스',
  '정도',
  '지역'],
 ['전주',
  '코스',
  '추천',
  '전주',
  '코스',
  '추천',
  '하세',
  '전주',
  '동물원',
  '기전',
  '전주',
  '한옥',
  '마을',
  '연못'],
 ['전주',
  '코스',
  '주세',
  '안녕',
  '하세',
  '전주',
  '당일',
  '코스',
  '주세',
  '전주',
  '동물원',
  '전주',
  '한옥',
  '마을',
  '전주',
  '수목원',
  '예술',
  '공장',
  '전주',
  '드림',
  '랜드',
  '당일',
  '코스',
  '주세',
  '자가용',
  '이동',
  '아래',
  '코스',
  '시간'],
 ['전주',
  '코스',
  '질문',
  '전주',
  '코스',
  '관련',
  '답변',
  '가족',
  '전주',
  '계획',
  '중이',
  '전주',
  '추천',
  '명소',
  '포함',
  '맞춤',
  '전주',
  '코스',
  '준비',
  '아래',
  '첨부',
  '일정'],
 ['당일',
  '전주',
  '코스',
  '처음',
  '전주',
  '전주',
  '한옥',
  '마을',
  '한복',
  '한옥',
  '마을',
  '전동',
  '성당',
  '경기',
  '자만',
  '벽화',
  '마을',
  '가기',
  '전주',
  '한옥',
  '마을'],
 ['초등',
  '아이',
  '전주',
  '코스',
  '추천',
  '부탁',
  '아이',
  '전주',
  '계획',
  '계시',
  '전주',
  '아이',
  '추천',
  '전주',
  '한옥',
  '마을',
  '계획',
  '두신',
  '장소',
  '전주',
  '한옥',
  '마을',
  '한복',
  '한옥',
  '마을',
  '사진'],
 ['전주',
  '코스',
  '전주',
  '코스',
  '추천',
  '전문',
  '아빠',
  '방학',
  '친구',
  '전주',
  '준비',
  '전주',
  '한옥',
  '마을',
  '중심',
  '터미널',
  '버스',
  '한옥',
  '마을'],
 ['전주',
  '순서',
  '주세',
  '전주',
  '공원',
  '전주',
  '동물원',
  '한옥',
  '마을',
  '남부',
  '시장',
  '전주',
  '시외버스',
  '공용',
  '터미널',
  '순서',
  '근처',
  '바닷가',
  '가요',
  '구경'],
 ['전주',
  '전주',
  '사람',
  '호텔',
  '가격',
  '얼마',
  '정도',
  '카페',
  '추천',
  '주세',
  '안녕',
  '하세',
  '전주',
  '계획',
  '중이',
  '한옥',
  '마을',
  '근처'],
 ['전주',
  '관련',
  '질문',
  '전주',
  '계획',
  '선택',
  '전주',
  '한옥',
  '마을',
  '자연',
  '경관',
  '음식',
  '동네',
  '시간',
  '한옥',
  '마을',
  '근처',
  '장소'],
 ['학생', '친구', '전주', '안녕', '하세', '여학생', '친구', '전주', '가기', '일본', '전주', '오타쿠'],
 ['모닝',
  '전주',
  '부모님',
  '전주',
  '명소',
  '식당',
  '추천',
  '전주',
  '한옥',
  '마을',
  '유명',
  '완산구',
  '덕진구',
  '추억',
  '장소'],
 ['전주',
  '이번',
  '여자',
  '친구',
  '전주',
  '경로',
  '주세',
  '토요일',
  '실내',
  '데이트',
  '가능',
  '감사',
  '숙소',
  '전주',
  '한옥',
  '마을',
  '근처',
  '한옥',
  '마을',
  '구경'],
 ['전주',
  '저녁',
  '전주',
  '산책길',
  '한옥',
  '마을',
  '근처',
  '야경',
  '일정',
  '관심',
  '테마',
  '사진',
  '카페',
  '체험',
  '맞춤',
  '추천',
  '전주'],
 ['전주',
  '코스',
  '추천',
  '이요',
  '영화제',
  '기간',
  '일정',
  '전주',
  '코스',
  '추천',
  '목적',
  '전주',
  '국제',
  '영화',
  '전주',
  '알짜',
  '배기',
  '추천',
  '주세',
  '전주'],
 ['전주',
  '전주',
  '커플',
  '추천',
  '주세',
  '숙소',
  '거리',
  '추천',
  '감사',
  '한옥',
  '마을',
  '변이',
  '도움',
  '한옥',
  '마을',
  '전주',
  '한옥',
  '마을',
  '전주',
  '전주',
  '거리',
  '전주',
  '추천'],
 ['추석',
  '전주',
  '전주',
  '그때',
  '한옥',
  '마을',
  '관광지',
  '추석',
  '당일',
  '전주',
  '이벤트',
  '진행',
  '한국',
  '관광',
  '공사',
  '숙박',
  '세일',
  '스타',
  '이벤트',
  '진행'],
 ['전주',
  '연령',
  '렌트카',
  '추천',
  '이번',
  '전주',
  '전주',
  '연령',
  '자동차',
  '추천',
  '가격',
  '렌트',
  '정도',
  '전주',
  '이상',
  '렌트',
  '가능',
  '자동차',
  '가격'],
 ['전주',
  '포항',
  '전주',
  '포항',
  '기차',
  '버스',
  '안녕',
  '하세',
  '전주',
  '포항',
  '기차',
  '버스',
  '장단점',
  '방법',
  '결정',
  '요소',
  '고려',
  '필요'],
 ['전주',
  '한옥',
  '이요',
  '이번',
  '남자',
  '친구',
  '전주',
  '가기',
  '전주',
  '한옥',
  '마을',
  '근처',
  '한옥',
  '느낌',
  '전주',
  '내부',
  '정감',
  '분위기',
  '답변',
  '부탁'],
 ['전주', '주세', '전주', '한옥', '마을', '유명', '완산구', '덕진구', '추억', '장소', '완산구', '덕진구'],
 ['전주',
  '엄마',
  '전주',
  '계획',
  '답변',
  '부탁',
  '기차',
  '고속버스',
  '전주',
  '도착',
  '관광',
  '이용',
  '교통수단',
  '추천',
  '서울'],
 ['전주',
  '당일',
  '전주',
  '당일',
  '계획',
  '중이',
  '전주',
  '한옥',
  '마을',
  '방법',
  '당일',
  '코스',
  '전주',
  '한옥',
  '마을',
  '방법',
  '택시',
  '버스',
  '전주',
  '한옥',
  '마을',
  '택시'],
 ['전주',
  '경비',
  '보통',
  '전주',
  '경비',
  '얼마',
  '정도',
  '숙소',
  '질문',
  '도움',
  '답변',
  '전주',
  '예산',
  '내외',
  '숙소'],
 ['전주',
  '커플',
  '전주',
  '도움',
  '남자',
  '친구',
  '이용',
  '이용',
  '요소',
  '고려',
  '만약',
  '교통',
  '체증',
  '예상',
  '날짜',
  '이용',
  '남자',
  '친구'],
 ['남해',
  '전주',
  '남해',
  '전주',
  '여행지',
  '추천',
  '주세',
  '보리',
  '다랭이',
  '독일',
  '마을',
  '전주',
  '한옥',
  '마을',
  '추천',
  '주세',
  '추천',
  '전주',
  '전주'],
 ['전주',
  '추천',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을'],
 ['전주',
  '코스',
  '질문',
  '코스',
  '주실',
  '전라도',
  '간적',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서'],
 ['전주',
  '전주',
  '비용',
  '얼마',
  '전주',
  '비용',
  '요소',
  '일반적',
  '다음',
  '항목',
  '포함',
  '교통',
  '전주',
  '이동',
  '교통',
  '비용'],
 ['전주',
  '코스',
  '전주',
  '전주',
  '국내',
  '전주',
  '티비',
  '전주',
  '코스',
  '주가',
  '볼만',
  '여수',
  '여수',
  '볼만',
  '제주도',
  '제주도',
  '볼만',
  '전문',
  '언서',
  '주달',
  '전주',
  '코스',
  '한옥',
  '마을',
  '시작'],
 ['전주',
  '당일',
  '혼자',
  '코스',
  '추천',
  '박물관',
  '미술관',
  '지역',
  '공간',
  '스토리',
  '안내',
  '해설',
  '문화',
  '코스',
  '방지',
  '예약금',

In [103]:
%%time
from apyori import apriori
rules = apriori(total_noun_list, # 2차원 데이터
                min_support = 0.15,
               min_confidence = 0.3,
               ) # 매개변수 : min_support min_confidence min_lift max_length 
rules = list(rules)

import pandas as pd
rules_df = pd.DataFrame(None, columns=['lhs','rhs','지지도','신뢰도','향상도'])

i = 0
for rule in rules :
    support = rule[1]
    order_st = rule[2]
    
    for item in order_st :
        lhs = [i for i in item[0]]
        rhs = [i for i in item[1]]
        confidence = item[2]
        lift = item[3]
        if lift > 1 :
            rules_df.loc[i] = [' '.join(lhs),' '.join(rhs),round(support,2),round(confidence,2),round(lift,2)]
            i +=1
rules_df.sort_values(by=['향상도','신뢰도','지지도'], ascending=False, inplace=True)
rules_df = rules_df.reset_index(drop=True)

CPU times: total: 5.27 s
Wall time: 5.26 s

In [104]:
# pd.options.display.max_rows
rules_df[:60]

            lhs          rhs   지지도  신뢰도   향상도
0         볼만 국내        주가 여수  0.16  1.0  5.99
1         주가 국내        볼만 여수  0.16  1.0  5.99
2         볼만 국내        여수 코스  0.16  1.0  5.99
3         볼만 국내        여수 티비  0.16  1.0  5.99
4         주가 국내        여수 코스  0.16  1.0  5.99
5         주가 국내        여수 티비  0.16  1.0  5.99
6         볼만 국내     전주 주가 여수  0.16  1.0  5.99
7         주가 국내     전주 볼만 여수  0.16  1.0  5.99
8      전주 볼만 국내        주가 여수  0.16  1.0  5.99
9      전주 주가 국내        볼만 여수  0.16  1.0  5.99
10        볼만 국내     전주 여수 코스  0.16  1.0  5.99
11     전주 볼만 국내        여수 코스  0.16  1.0  5.99
12        볼만 국내     전주 여수 티비  0.16  1.0  5.99
13     전주 볼만 국내        여수 티비  0.16  1.0  5.99
14        볼만 국내     주가 여수 코스  0.16  1.0  5.99
15        주가 국내     볼만 여수 코스  0.16  1.0  5.99
16     주가 볼만 국내        여수 코스  0.16  1.0  5.99
17     볼만 코스 국내        주가 여수  0.16  1.0  5.99
18     주가 코스 국내        볼만 여수  0.16  1.0  5.99
19        볼만 국내     주가 여수 티비  0.16  1.0  5.99
20        주가 국내     볼만 여수 티비  0.16  1.0  5.99
21     주가 볼만 국내        여수 티비  0.16  1.0  5.99
22     볼만 국내 티비        주가 여수  0.16  1.0  5.99
23     주가 국내 티비        볼만 여수  0.16  1.0  5.99
24        볼만 국내     여수 코스 티비  0.16  1.0  5.99
25     볼만 코스 국내        여수 티비  0.16  1.0  5.99
26     볼만 국내 티비        여수 코스  0.16  1.0  5.99
27        주가 국내     전주 여수 코스  0.16  1.0  5.99
28     전주 주가 국내        여수 코스  0.16  1.0  5.99
29        주가 국내     전주 여수 티비  0.16  1.0  5.99
30     전주 주가 국내        여수 티비  0.16  1.0  5.99
31        주가 국내     여수 코스 티비  0.16  1.0  5.99
32     주가 코스 국내        여수 티비  0.16  1.0  5.99
33     주가 국내 티비        여수 코스  0.16  1.0  5.99
34        볼만 국내  전주 주가 여수 코스  0.16  1.0  5.99
35        주가 국내  전주 볼만 여수 코스  0.16  1.0  5.99
36     전주 볼만 국내     주가 여수 코스  0.16  1.0  5.99
37     주가 볼만 국내     전주 여수 코스  0.16  1.0  5.99
38     볼만 코스 국내     전주 주가 여수  0.16  1.0  5.99
39     전주 주가 국내     볼만 여수 코스  0.16  1.0  5.99
40     주가 코스 국내     전주 볼만 여수  0.16  1.0  5.99
41  전주 볼만 주가 국내        여수 코스  0.16  1.0  5.99
42  전주 볼만 코스 국내        주가 여수  0.16  1.0  5.99
43  전주 주가 코스 국내        볼만 여수  0.16  1.0  5.99
44        볼만 국내  전주 주가 여수 티비  0.16  1.0  5.99
45        주가 국내  전주 볼만 여수 티비  0.16  1.0  5.99
46     전주 볼만 국내     주가 여수 티비  0.16  1.0  5.99
47     주가 볼만 국내     전주 여수 티비  0.16  1.0  5.99
48     볼만 국내 티비     전주 주가 여수  0.16  1.0  5.99
49     전주 주가 국내     볼만 여수 티비  0.16  1.0  5.99
50     주가 국내 티비     전주 볼만 여수  0.16  1.0  5.99
51  전주 볼만 주가 국내        여수 티비  0.16  1.0  5.99
52  전주 볼만 국내 티비        주가 여수  0.16  1.0  5.99
53  전주 주가 국내 티비        볼만 여수  0.16  1.0  5.99
54        볼만 국내  전주 여수 코스 티비  0.16  1.0  5.99
55     전주 볼만 국내     여수 코스 티비  0.16  1.0  5.99
56     볼만 코스 국내     전주 여수 티비  0.16  1.0  5.99
57     볼만 국내 티비     전주 여수 코스  0.16  1.0  5.99
58  전주 볼만 코스 국내        여수 티비  0.16  1.0  5.99
59  전주 볼만 국내 티비        여수 코스  0.16  1.0  5.99