In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:86% !important;}
div.cell.code_cell.rendered{width:100%;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:15pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:15px;}
</style>
"""))

# Attention으로 번역기 만들기
- Attention

## 1. 패키지 import 및 하이퍼파라미터
- 하이터 파라미터 : 모델의 정확도 및 학습속도에 영향을 미치는 변수

In [2]:
import numpy as np
import pandas as pd
from time import time

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Dropout, LSTM, Attention, Concatenate
from tensorflow.keras.utils import to_categorical

# 하이퍼 파라미터
MY_HIDDEN = 128 # hidden layer units 설정
MY_EPOCH = 500

## 2. 번역 데이터 불러오기

In [3]:
raw = pd.read_csv('data/translate.csv', header=None) # 영어 알파벳 4개 -> 한글 번역 2글자로
eng_kor = raw.values.tolist() # DataFrame => list
print('영어-한글 번역 데이터 :',eng_kor[:3])
print('영어-한글 번역 데이터 수 :',len(eng_kor))

영어-한글 번역 데이터 : [['cold', '감기'], ['come', '오다'], ['cook', '요리']]
영어-한글 번역 데이터 수 : 110

## 3. 영어 알파벳과 한글 문자 리스트 만들기

In [4]:
# 영어 알파벳 리스트(e_alpha)
e_alpha = [c for c in 'SEPabcdefghijklmnopqrstuvwxyz']
# print(e_alpha)
# {c:i for i, c in enumerate(e_alpha)}

# 한글 문자 리스트(k_ch,k_alpha)
k_ch = sorted(set(''.join([data[1] for data in eng_kor])))
# print(k_ch)
k_alpha = pd.read_csv('data/korean.csv', header=None)[0].tolist()
k_alpha == k_ch # 내용(값,index)이 모두 같을 때

# 순서는 무시하고 내용만 같은 지
from collections import Counter
list1 = ['가','간','나']
list2 = ['간','나','가']
list_1_count = Counter(list1)
list_2_count = Counter(list2)
list_1_count== list_2_count

True

In [5]:
alpha = e_alpha + k_ch
print('영어와 한글 알파벳 :',alpha)
alpha_total_size = len(alpha)
print('전체 알파벳 개수(원핫인코딩 할 size) :',alpha_total_size)
print('한글 알파벳 개수 :',len(k_alpha))

영어와 한글 알파벳 : ['S', 'E', 'P', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '가', '각', '간', '감', '개', '거', '것', '게', '계', '고', '관', '광', '구', '굴', '규', '그', '금', '기', '깊', '나', '날', '남', '내', '넓', '녀', '노', '놀', '농', '높', '뉴', '늦', '다', '단', '도', '동', '들', '람', '랑', '래', '램', '류', '름', '릎', '리', '많', '망', '매', '머', '먼', '멍', '메', '명', '모', '목', '무', '물', '미', '바', '반', '방', '번', '복', '부', '분', '붕', '비', '뿌', '사', '상', '색', '생', '서', '선', '소', '손', '수', '쉽', '스', '시', '식', '실', '싸', '아', '약', '얇', '어', '언', '얼', '여', '연', '오', '옥', '왼', '요', '용', '우', '운', '움', '위', '유', '은', '을', '음', '의', '이', '익', '인', '읽', '입', '자', '작', '장', '적', '제', '좋', '주', '지', '짜', '쪽', '찾', '책', '출', '칙', '크', '키', '탈', '택', '통', '파', '팔', '편', '피', '핑', '한', '합', '해', '행', '험', '회', '획', '휴', '흐']
전체 알파벳 개수(원핫인코딩 할 size) : 171
한글 알파벳 개수 : 142

## 4. 문자당 num을 갖는 dict 만들기

In [6]:
char_to_num = {c:i for i,c in enumerate(alpha)}
num_to_char = {i:c for i,c in enumerate(alpha)}
print(char_to_num, num_to_char)

{'S': 0, 'E': 1, 'P': 2, 'a': 3, 'b': 4, 'c': 5, 'd': 6, 'e': 7, 'f': 8, 'g': 9, 'h': 10, 'i': 11, 'j': 12, 'k': 13, 'l': 14, 'm': 15, 'n': 16, 'o': 17, 'p': 18, 'q': 19, 'r': 20, 's': 21, 't': 22, 'u': 23, 'v': 24, 'w': 25, 'x': 26, 'y': 27, 'z': 28, '가': 29, '각': 30, '간': 31, '감': 32, '개': 33, '거': 34, '것': 35, '게': 36, '계': 37, '고': 38, '관': 39, '광': 40, '구': 41, '굴': 42, '규': 43, '그': 44, '금': 45, '기': 46, '깊': 47, '나': 48, '날': 49, '남': 50, '내': 51, '넓': 52, '녀': 53, '노': 54, '놀': 55, '농': 56, '높': 57, '뉴': 58, '늦': 59, '다': 60, '단': 61, '도': 62, '동': 63, '들': 64, '람': 65, '랑': 66, '래': 67, '램': 68, '류': 69, '름': 70, '릎': 71, '리': 72, '많': 73, '망': 74, '매': 75, '머': 76, '먼': 77, '멍': 78, '메': 79, '명': 80, '모': 81, '목': 82, '무': 83, '물': 84, '미': 85, '바': 86, '반': 87, '방': 88, '번': 89, '복': 90, '부': 91, '분': 92, '붕': 93, '비': 94, '뿌': 95, '사': 96, '상': 97, '색': 98, '생': 99, '서': 100, '선': 101, '소': 102, '손': 103, '수': 104, '쉽': 105, '스': 106, '시': 107, '식': 108, '실': 109, '싸': 110, '아': 111, '약': 112, '얇': 113, '어': 114, '언': 115, '얼': 116, '여': 117, '연': 118, '오': 119, '옥': 120, '왼': 121, '요': 122, '용': 123, '우': 124, '운': 125, '움': 126, '위': 127, '유': 128, '은': 129, '을': 130, '음': 131, '의': 132, '이': 133, '익': 134, '인': 135, '읽': 136, '입': 137, '자': 138, '작': 139, '장': 140, '적': 141, '제': 142, '좋': 143, '주': 144, '지': 145, '짜': 146, '쪽': 147, '찾': 148, '책': 149, '출': 150, '칙': 151, '크': 152, '키': 153, '탈': 154, '택': 155, '통': 156, '파': 157, '팔': 158, '편': 159, '피': 160, '핑': 161, '한': 162, '합': 163, '해': 164, '행': 165, '험': 166, '회': 167, '획': 168, '휴': 169, '흐': 170} {0: 'S', 1: 'E', 2: 'P', 3: 'a', 4: 'b', 5: 'c', 6: 'd', 7: 'e', 8: 'f', 9: 'g', 10: 'h', 11: 'i', 12: 'j', 13: 'k', 14: 'l', 15: 'm', 16: 'n', 17: 'o', 18: 'p', 19: 'q', 20: 'r', 21: 's', 22: 't', 23: 'u', 24: 'v', 25: 'w', 26: 'x', 27: 'y', 28: 'z', 29: '가', 30: '각', 31: '간', 32: '감', 33: '개', 34: '거', 35: '것', 36: '게', 37: '계', 38: '고', 39: '관', 40: '광', 41: '구', 42: '굴', 43: '규', 44: '그', 45: '금', 46: '기', 47: '깊', 48: '나', 49: '날', 50: '남', 51: '내', 52: '넓', 53: '녀', 54: '노', 55: '놀', 56: '농', 57: '높', 58: '뉴', 59: '늦', 60: '다', 61: '단', 62: '도', 63: '동', 64: '들', 65: '람', 66: '랑', 67: '래', 68: '램', 69: '류', 70: '름', 71: '릎', 72: '리', 73: '많', 74: '망', 75: '매', 76: '머', 77: '먼', 78: '멍', 79: '메', 80: '명', 81: '모', 82: '목', 83: '무', 84: '물', 85: '미', 86: '바', 87: '반', 88: '방', 89: '번', 90: '복', 91: '부', 92: '분', 93: '붕', 94: '비', 95: '뿌', 96: '사', 97: '상', 98: '색', 99: '생', 100: '서', 101: '선', 102: '소', 103: '손', 104: '수', 105: '쉽', 106: '스', 107: '시', 108: '식', 109: '실', 110: '싸', 111: '아', 112: '약', 113: '얇', 114: '어', 115: '언', 116: '얼', 117: '여', 118: '연', 119: '오', 120: '옥', 121: '왼', 122: '요', 123: '용', 124: '우', 125: '운', 126: '움', 127: '위', 128: '유', 129: '은', 130: '을', 131: '음', 132: '의', 133: '이', 134: '익', 135: '인', 136: '읽', 137: '입', 138: '자', 139: '작', 140: '장', 141: '적', 142: '제', 143: '좋', 144: '주', 145: '지', 146: '짜', 147: '쪽', 148: '찾', 149: '책', 150: '출', 151: '칙', 152: '크', 153: '키', 154: '탈', 155: '택', 156: '통', 157: '파', 158: '팔', 159: '편', 160: '피', 161: '핑', 162: '한', 163: '합', 164: '해', 165: '행', 166: '험', 167: '회', 168: '획', 169: '휴', 170: '흐'}

In [7]:
data = eng_kor[0]
print(data)
print('인코더 입력 :',char_to_num['c'],char_to_num['o'],char_to_num['l'],char_to_num['d'])
print('인코더 입력(원핫인코딩 전) :',[char_to_num[c] for c in data[0]])
print('디코더 입력(원핫인코딩 전) :',[char_to_num[c] for c in 'S' + data[1]])
print('디코더 출력(원핫인코딩 X) :',[char_to_num[c] for c in data[1]+'E']) # 원핫 인코딩 대신 loss = sparse_categorical_crossentropy

['cold', '감기']
인코더 입력 : 5 17 14 6
인코더 입력(원핫인코딩 전) : [5, 17, 14, 6]
디코더 입력(원핫인코딩 전) : [0, 32, 46]
디코더 출력(원핫인코딩 X) : [32, 46, 1]

In [55]:
# 희소행렬의 원핫 인코딩 방법 1 (희소행렬에서는 pd.get_dummies([2,8,7]) 사용 불가(size 조절이 불가 -> 전체 원소개수만 가능))

In [8]:
# pd.get_dummies([5,17,14,6]) # 사용 불가
to_categorical([5,7,6,8],
#                num_classes=alpha_total_size, # 실제로 사용했어야 하는 값
              num_classes=10, # 학생의 학습을 위해 교본의 사이즈를 10으로 고정해서 사용
              )

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)

In [9]:
# 희소행렬의 원핫 인코딩 방법 2
np.eye(10)[[5,7,6,8]]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

## 5. 인코더 입력, 디코더 입력, 디코더 출력
- 인코더 입력 데이터 : 영어 알파벳 -> 숫자 -> 원핫인코딩, shape = (110, 4, 171) array
- 디코더 입력 데이터 : 'S' + 한글 문자 -> 숫자 -> 원핫인코딩, shape = (110, 1('S') + 2 ,171) array
- 디코더 출력 데이터 : 한글 문자 + 'E' -> 숫자 shape = (110, 2+1('E')) list => 최종 shape (110, 3, 1) array로

In [11]:
def encoding(eng_kor = eng_kor) :
    ''' 
    [['eng4' : 'kor2']] 형태 데이터가 입력되면 인코더 입력, 디코더 입력, 디코더 출력 순으로 반환함
    '''
    enc_in = [] # 인코더 입력
    dec_in = [] # 디코더 입력
    dec_out = [] # 디코더 출력
    for data in eng_kor :
        # 인코더 입력 데이터(영어 알파벳 -> 숫자 -> 원핫인코딩)
        eng = [char_to_num[c] for c in data[0]]
        eng_one = np.eye(alpha_total_size)[eng]
#         print('영어 :',eng, eng_one)
        enc_in.append(eng_one) # eng_one의 shape = (4,171)
    
        # 디코더 입력 데이터('S' + 한글 문자 -> 숫자 -> 원핫인코딩)
        kor = [char_to_num[c] for c in 'S' + data[1]]
        kor_one = to_categorical(kor,num_classes=alpha_total_size) # np.eye(alpha_total_size)[kor]
#         print('한글 :',kor,kor_one)
        dec_in.append(kor_one) # kor_one의 shape = (1('S')+2 = 3 ,171)
        
        # 디코더 출력 데이터(한글 문자 + 'E' -> 숫자)
        kor = [char_to_num[c] for c in data[1] + 'E']
#         print(kor)
        dec_out.append(kor)
    return enc_in, dec_in, dec_out

In [12]:
sample = [['cold','감기'],['wood','나무']]
x_enc, x_dec, y_dec = encoding(sample)
X_enc = np.array(x_enc)
X_enc.shape # shape (2 단어수, 4 단어 당 문자 수, 171 학습에 필요한, 단어를 찢어서 만든 문자의 수)
X_dec = np.array(x_dec)
X_dec.shape # shape (2 단어수, 3 "S단어"의 문자 수, 171 학습에 필요한, 단어를 찢어서 만든 문자의 수)
Y_dec = np.array(y_dec)
Y_dec.shape # shape (2 단어 수, 3"단어E"의 문자수), 원핫인코딩 X loss = sparse_categorical_crossentropy로 해결, 그러나 입력하는 값들과 차원을 맞춰야함

(2, 3)

In [13]:
# shape (2 단어 수, 3"단어E"의 문자수), 원핫인코딩 X loss = sparse_categorical_crossentropy로 해결, 그러나 입력하는 값들과 차원을 맞춰야함
# 축 증가 방법 1
Y_dec.reshape(2,3,1)
# 축 증가 방법 2 : 맨 마지막 축 증가하는 함수
np.expand_dims(Y_dec, axis=-1)
# 축 증가 방법 3
Y_dec[...,np.newaxis]
# 축 증가 방법 4
Y_dec[:,:,None]

array([[[32],
        [46],
        [ 1]],

       [[48],
        [83],
        [ 1]]])

## 6. 전체 입력데이터, 타겟데이터 준비

In [14]:
x_inc, x_dec, y_dec = encoding()
type(x_inc),type(x_dec),type(y_dec) # 타입 변환 필요
X_enc = np.array(x_inc)
X_dec = np.array(x_dec)
# Y_dec = np.array(y_dec)[...,np.newaxis]
Y_dec = np.expand_dims(y_dec,-1) # 리스트 타입에서도 바로 사용이 가능
X_enc.shape, X_dec.shape, Y_dec.shape

((110, 4, 171), (110, 3, 171), (110, 3, 1))

## 7. 모델 구현

### 7.1 Seq2Seq

In [122]:
# 인코더 LSTM
ENC_IN = Input((X_enc.shape[1],alpha_total_size))
_, state_h, state_c = LSTM(units = MY_HIDDEN # 128
         ,return_state=True,
#          return_sequences=True, # LSTM 윗 출력 안받음
                          )(ENC_IN) 

# 인코더와 디코더 연결 고리
LINK = [state_h, state_c]

# 디코더 LSTM
DEC_IN = Input(shape = (Y_dec.shape[1],alpha_total_size))
DEC_MID = LSTM(units = MY_HIDDEN,
#               return_state=False, # 기본값
              return_sequences=True, # 윗출력을 받겠다 => 시퀀스 정보가 담긴 데이터를 받겠다
              )(DEC_IN,
               initial_state=LINK)

# 최종 출력층
DEC_OUT = Dense(units = alpha_total_size,
               activation='softmax')(DEC_MID)

# 모델
model = Model(inputs=[ENC_IN,DEC_IN],
              outputs = DEC_OUT)

model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_6 (InputLayer)           [(None, 4, 171)]     0           []

 input_7 (InputLayer)           [(None, 3, 171)]     0           []

 lstm_5 (LSTM)                  [(None, 128),        153600      ['input_6[0][0]']
                                 (None, 128),
                                 (None, 128)]

 lstm_6 (LSTM)                  (None, 3, 128)       153600      ['input_7[0][0]',
                                                                  'lstm_5[0][1]',
                                                                  'lstm_5[0][2]']

 dense (Dense)                  (None, 3, 171)       22059       ['lstm_6[0][0]']

==================================================================================================
Total params: 329,259
Trainable params: 329,259
Non-trainable params: 0
__________________________________________________________________________________________________

## 7.2 Attention

In [16]:
# 인코더 입력
ENC_IN = Input(shape=(4,alpha_total_size)) # alpha_total_size = 171

# 인코더 LSTM : 모든 방향성 자료 출력 필요. return_sequences=True / 결과값 출력, return_state=True / state_h, state_c 
ENC_OUt, state_h, state_c = LSTM(units = MY_HIDDEN,
                                return_sequences=True,
                                return_state=True)(ENC_IN)

# state_h, state_c 전송 계층
LINK = [state_h,state_c]

# 디코더 입력
DEC_IN = Input(shape=(3,alpha_total_size))

# 디코더 LSTM : 상위방향, 결과값 전송 필요(return_sequences = True)
DEC_LSTM_OUT, _, _ = LSTM(units=MY_HIDDEN, # 128
                          return_sequences=True,
                          return_state=True)(DEC_IN,
                                            initial_state=LINK)

# Attention
CONTEXT_VECTOR = Attention()([DEC_LSTM_OUT,ENC_OUt])

# 컨텍스트 벡터와 디코더 LSTM 결과를 Concatenate
CONTEXT_AND_LSTM_OUT= Concatenate()([CONTEXT_VECTOR,
                                     DEC_LSTM_OUT])
OUT = Dense(units = alpha_total_size, activation='softmax')(CONTEXT_AND_LSTM_OUT)

# 모델 정의
model = Model(inputs=[ENC_IN,DEC_IN],outputs=OUT)
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_3 (InputLayer)           [(None, 4, 171)]     0           []

 input_4 (InputLayer)           [(None, 3, 171)]     0           []

 lstm_2 (LSTM)                  [(None, 4, 128),     153600      ['input_3[0][0]']
                                 (None, 128),
                                 (None, 128)]

 lstm_3 (LSTM)                  [(None, 3, 128),     153600      ['input_4[0][0]',
                                 (None, 128),                     'lstm_2[0][1]',
                                 (None, 128)]                     'lstm_2[0][2]']

 attention_1 (Attention)        (None, 3, 128)       0           ['lstm_3[0][0]',
                                                                  'lstm_2[0][0]']

 concatenate_1 (Concatenate)    (None, 3, 256)       0           ['attention_1[0][0]',
                                                                  'lstm_3[0][0]']

 dense_1 (Dense)                (None, 3, 171)       43947       ['concatenate_1[0][0]']

==================================================================================================
Total params: 351,147
Trainable params: 351,147
Non-trainable params: 0
__________________________________________________________________________________________________

## 8. 모델 학습과정 설정 & 학습

In [17]:
model.compile(loss = 'sparse_categorical_crossentropy',
             optimizer = 'rmsprop',
             metrics=['accuracy'], # meticts = None 시 loss만 로그 출력
             )
begin = time()
model.fit([X_enc,X_dec],Y_dec,
         epochs=MY_EPOCH,
          workers=-1,
         )
end = time()
print('학습시간 :', end-begin)

Epoch 1/500
4/4 [==============================] - 5s 15ms/step - loss: 5.1107 - accuracy: 0.2242
Epoch 2/500
4/4 [==============================] - 0s 12ms/step - loss: 4.9408 - accuracy: 0.3333
Epoch 3/500
4/4 [==============================] - 0s 12ms/step - loss: 4.2026 - accuracy: 0.3333
Epoch 4/500
4/4 [==============================] - 0s 11ms/step - loss: 3.4683 - accuracy: 0.3333
Epoch 5/500
4/4 [==============================] - 0s 11ms/step - loss: 3.4078 - accuracy: 0.3333
Epoch 6/500
4/4 [==============================] - 0s 12ms/step - loss: 3.3631 - accuracy: 0.3333
Epoch 7/500
4/4 [==============================] - 0s 12ms/step - loss: 3.3286 - accuracy: 0.3333
Epoch 8/500
4/4 [==============================] - 0s 11ms/step - loss: 3.2940 - accuracy: 0.3333
Epoch 9/500
4/4 [==============================] - 0s 9ms/step - loss: 3.2646 - accuracy: 0.3333
Epoch 10/500
4/4 [==============================] - 0s 11ms/step - loss: 3.2464 - accuracy: 0.3333
Epoch 11/500
4/4 [==============================] - 0s 11ms/step - loss: 3.2239 - accuracy: 0.3333
Epoch 12/500
4/4 [==============================] - 0s 11ms/step - loss: 3.1941 - accuracy: 0.3394
Epoch 13/500
4/4 [==============================] - 0s 11ms/step - loss: 3.1648 - accuracy: 0.3394
Epoch 14/500
4/4 [==============================] - 0s 9ms/step - loss: 3.1473 - accuracy: 0.3394
Epoch 15/500
4/4 [==============================] - 0s 11ms/step - loss: 3.1215 - accuracy: 0.3394
Epoch 16/500
4/4 [==============================] - 0s 11ms/step - loss: 3.0990 - accuracy: 0.3485
Epoch 17/500
4/4 [==============================] - 0s 11ms/step - loss: 3.0811 - accuracy: 0.3485
Epoch 18/500
4/4 [==============================] - 0s 12ms/step - loss: 3.0607 - accuracy: 0.3667
Epoch 19/500
4/4 [==============================] - 0s 12ms/step - loss: 3.0370 - accuracy: 0.3545
Epoch 20/500
4/4 [==============================] - 0s 11ms/step - loss: 3.0214 - accuracy: 0.3697
Epoch 21/500
4/4 [==============================] - 0s 11ms/step - loss: 3.0002 - accuracy: 0.3667
Epoch 22/500
4/4 [==============================] - 0s 12ms/step - loss: 2.9733 - accuracy: 0.3667
Epoch 23/500
4/4 [==============================] - 0s 11ms/step - loss: 2.9517 - accuracy: 0.3697
Epoch 24/500
4/4 [==============================] - 0s 9ms/step - loss: 2.9346 - accuracy: 0.3727
Epoch 25/500
4/4 [==============================] - 0s 11ms/step - loss: 2.9036 - accuracy: 0.3697
Epoch 26/500
4/4 [==============================] - 0s 11ms/step - loss: 2.8789 - accuracy: 0.3758
Epoch 27/500
4/4 [==============================] - 0s 12ms/step - loss: 2.8553 - accuracy: 0.3727
Epoch 28/500
4/4 [==============================] - 0s 10ms/step - loss: 2.8407 - accuracy: 0.3697
Epoch 29/500
4/4 [==============================] - 0s 10ms/step - loss: 2.7969 - accuracy: 0.3818
Epoch 30/500
4/4 [==============================] - 0s 11ms/step - loss: 2.7635 - accuracy: 0.3848
Epoch 31/500
4/4 [==============================] - 0s 11ms/step - loss: 2.7410 - accuracy: 0.3939
Epoch 32/500
4/4 [==============================] - 0s 11ms/step - loss: 2.6981 - accuracy: 0.3909
Epoch 33/500
4/4 [==============================] - 0s 10ms/step - loss: 2.6557 - accuracy: 0.3970
Epoch 34/500
4/4 [==============================] - 0s 11ms/step - loss: 2.6203 - accuracy: 0.3939
Epoch 35/500
4/4 [==============================] - 0s 11ms/step - loss: 2.5876 - accuracy: 0.3970
Epoch 36/500
4/4 [==============================] - 0s 11ms/step - loss: 2.5253 - accuracy: 0.4000
Epoch 37/500
4/4 [==============================] - 0s 11ms/step - loss: 2.4793 - accuracy: 0.4061
Epoch 38/500
4/4 [==============================] - 0s 12ms/step - loss: 2.4755 - accuracy: 0.4030
Epoch 39/500
4/4 [==============================] - 0s 10ms/step - loss: 2.3845 - accuracy: 0.4182
Epoch 40/500
4/4 [==============================] - 0s 12ms/step - loss: 2.3322 - accuracy: 0.4152
Epoch 41/500
4/4 [==============================] - 0s 11ms/step - loss: 2.2779 - accuracy: 0.4273
Epoch 42/500
4/4 [==============================] - 0s 14ms/step - loss: 2.2279 - accuracy: 0.4242
Epoch 43/500
4/4 [==============================] - 0s 9ms/step - loss: 2.2229 - accuracy: 0.4273
Epoch 44/500
4/4 [==============================] - 0s 10ms/step - loss: 2.1212 - accuracy: 0.4424
Epoch 45/500
4/4 [==============================] - 0s 11ms/step - loss: 2.0659 - accuracy: 0.4848
Epoch 46/500
4/4 [==============================] - 0s 10ms/step - loss: 2.0077 - accuracy: 0.4848
Epoch 47/500
4/4 [==============================] - 0s 11ms/step - loss: 2.0011 - accuracy: 0.4879
Epoch 48/500
4/4 [==============================] - 0s 11ms/step - loss: 1.8975 - accuracy: 0.5091
Epoch 49/500
4/4 [==============================] - 0s 10ms/step - loss: 1.8511 - accuracy: 0.5424
Epoch 50/500
4/4 [==============================] - 0s 10ms/step - loss: 1.7847 - accuracy: 0.6030
Epoch 51/500
4/4 [==============================] - 0s 11ms/step - loss: 1.7297 - accuracy: 0.6152
Epoch 52/500
4/4 [==============================] - 0s 11ms/step - loss: 1.6715 - accuracy: 0.6061
Epoch 53/500
4/4 [==============================] - 0s 11ms/step - loss: 1.6230 - accuracy: 0.6667
Epoch 54/500
4/4 [==============================] - 0s 11ms/step - loss: 1.6455 - accuracy: 0.6606
Epoch 55/500
4/4 [==============================] - 0s 10ms/step - loss: 1.5092 - accuracy: 0.6970
Epoch 56/500
4/4 [==============================] - 0s 10ms/step - loss: 1.4585 - accuracy: 0.7061
Epoch 57/500
4/4 [==============================] - 0s 11ms/step - loss: 1.4071 - accuracy: 0.7576
Epoch 58/500
4/4 [==============================] - 0s 15ms/step - loss: 1.3594 - accuracy: 0.7758
Epoch 59/500
4/4 [==============================] - 0s 9ms/step - loss: 1.3259 - accuracy: 0.7788
Epoch 60/500
4/4 [==============================] - 0s 10ms/step - loss: 1.2987 - accuracy: 0.7848
Epoch 61/500
4/4 [==============================] - 0s 10ms/step - loss: 1.2224 - accuracy: 0.8091
Epoch 62/500
4/4 [==============================] - 0s 10ms/step - loss: 1.1791 - accuracy: 0.8333
Epoch 63/500
4/4 [==============================] - 0s 10ms/step - loss: 1.1322 - accuracy: 0.8424
Epoch 64/500
4/4 [==============================] - 0s 10ms/step - loss: 1.1206 - accuracy: 0.8303
Epoch 65/500
4/4 [==============================] - 0s 9ms/step - loss: 1.0494 - accuracy: 0.8545
Epoch 66/500
4/4 [==============================] - 0s 10ms/step - loss: 1.0064 - accuracy: 0.8697
Epoch 67/500
4/4 [==============================] - 0s 9ms/step - loss: 0.9747 - accuracy: 0.8667
Epoch 68/500
4/4 [==============================] - 0s 10ms/step - loss: 0.9384 - accuracy: 0.8879
Epoch 69/500
4/4 [==============================] - 0s 10ms/step - loss: 0.8965 - accuracy: 0.9000
Epoch 70/500
4/4 [==============================] - 0s 9ms/step - loss: 0.8651 - accuracy: 0.8939
Epoch 71/500
4/4 [==============================] - 0s 10ms/step - loss: 0.8455 - accuracy: 0.9061
Epoch 72/500
4/4 [==============================] - 0s 11ms/step - loss: 0.8094 - accuracy: 0.8970
Epoch 73/500
4/4 [==============================] - 0s 10ms/step - loss: 0.7618 - accuracy: 0.9212
Epoch 74/500
4/4 [==============================] - 0s 10ms/step - loss: 0.7386 - accuracy: 0.9273
Epoch 75/500
4/4 [==============================] - 0s 13ms/step - loss: 0.7044 - accuracy: 0.9152
Epoch 76/500
4/4 [==============================] - 0s 10ms/step - loss: 0.6789 - accuracy: 0.9242
Epoch 77/500
4/4 [==============================] - 0s 12ms/step - loss: 0.6446 - accuracy: 0.9333
Epoch 78/500
4/4 [==============================] - 0s 12ms/step - loss: 0.6205 - accuracy: 0.9424
Epoch 79/500
4/4 [==============================] - 0s 11ms/step - loss: 0.5943 - accuracy: 0.9394
Epoch 80/500
4/4 [==============================] - 0s 11ms/step - loss: 0.6104 - accuracy: 0.9485
Epoch 81/500
4/4 [==============================] - 0s 10ms/step - loss: 0.5456 - accuracy: 0.9485
Epoch 82/500
4/4 [==============================] - 0s 10ms/step - loss: 0.5241 - accuracy: 0.9545
Epoch 83/500

4/4 [==============================] - 0s 11ms/step - loss: 0.5040 - accuracy: 0.9576
Epoch 84/500
4/4 [==============================] - 0s 9ms/step - loss: 0.4798 - accuracy: 0.9545
Epoch 85/500
4/4 [==============================] - 0s 10ms/step - loss: 0.4605 - accuracy: 0.9606
Epoch 86/500
4/4 [==============================] - 0s 9ms/step - loss: 0.4444 - accuracy: 0.9667
Epoch 87/500
4/4 [==============================] - 0s 10ms/step - loss: 0.4402 - accuracy: 0.9758
Epoch 88/500
4/4 [==============================] - 0s 10ms/step - loss: 0.4032 - accuracy: 0.9667
Epoch 89/500
4/4 [==============================] - 0s 11ms/step - loss: 0.3879 - accuracy: 0.9697
Epoch 90/500
4/4 [==============================] - 0s 11ms/step - loss: 0.3754 - accuracy: 0.9788
Epoch 91/500
4/4 [==============================] - 0s 12ms/step - loss: 0.3565 - accuracy: 0.9848
Epoch 92/500
4/4 [==============================] - 0s 12ms/step - loss: 0.3465 - accuracy: 0.9788
Epoch 93/500
4/4 [==============================] - 0s 10ms/step - loss: 0.3312 - accuracy: 0.9758
Epoch 94/500
4/4 [==============================] - 0s 10ms/step - loss: 0.3070 - accuracy: 0.9848
Epoch 95/500
4/4 [==============================] - 0s 9ms/step - loss: 0.2979 - accuracy: 0.9879
Epoch 96/500
4/4 [==============================] - 0s 11ms/step - loss: 0.2881 - accuracy: 0.9909
Epoch 97/500
4/4 [==============================] - 0s 10ms/step - loss: 0.2770 - accuracy: 0.9848
Epoch 98/500
4/4 [==============================] - 0s 9ms/step - loss: 0.2588 - accuracy: 0.9818
Epoch 99/500
4/4 [==============================] - 0s 10ms/step - loss: 0.2495 - accuracy: 0.9879
Epoch 100/500
4/4 [==============================] - 0s 10ms/step - loss: 0.2412 - accuracy: 0.9818
Epoch 101/500
4/4 [==============================] - 0s 10ms/step - loss: 0.2298 - accuracy: 0.9879
Epoch 102/500
4/4 [==============================] - 0s 8ms/step - loss: 0.2173 - accuracy: 0.9909
Epoch 103/500
4/4 [==============================] - 0s 10ms/step - loss: 0.2200 - accuracy: 0.9909
Epoch 104/500
4/4 [==============================] - 0s 10ms/step - loss: 0.1994 - accuracy: 0.9909
Epoch 105/500
4/4 [==============================] - 0s 13ms/step - loss: 0.1915 - accuracy: 0.9848
Epoch 106/500
4/4 [==============================] - 0s 10ms/step - loss: 0.1838 - accuracy: 0.9879
Epoch 107/500
4/4 [==============================] - 0s 10ms/step - loss: 0.1704 - accuracy: 0.9909
Epoch 108/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1647 - accuracy: 0.9879
Epoch 109/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1600 - accuracy: 0.9970
Epoch 110/500
4/4 [==============================] - 0s 10ms/step - loss: 0.1498 - accuracy: 0.9939
Epoch 111/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1445 - accuracy: 0.9939
Epoch 112/500
4/4 [==============================] - 0s 10ms/step - loss: 0.1390 - accuracy: 0.9939
Epoch 113/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1351 - accuracy: 0.9909
Epoch 114/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1268 - accuracy: 0.9939
Epoch 115/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1188 - accuracy: 0.9970
Epoch 116/500
4/4 [==============================] - 0s 9ms/step - loss: 0.1134 - accuracy: 0.9939
Epoch 117/500
4/4 [==============================] - 0s 8ms/step - loss: 0.1070 - accuracy: 1.0000
Epoch 118/500
4/4 [==============================] - 0s 10ms/step - loss: 0.1059 - accuracy: 0.9939
Epoch 119/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0990 - accuracy: 0.9939
Epoch 120/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0973 - accuracy: 0.9909
Epoch 121/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0921 - accuracy: 0.9970
Epoch 122/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0857 - accuracy: 0.9970
Epoch 123/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0801 - accuracy: 1.0000
Epoch 124/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0792 - accuracy: 0.9909
Epoch 125/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0788 - accuracy: 0.9939
Epoch 126/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0757 - accuracy: 0.9970
Epoch 127/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0682 - accuracy: 0.9939
Epoch 128/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0658 - accuracy: 0.9939
Epoch 129/500
4/4 [==============================] - 0s 14ms/step - loss: 0.0605 - accuracy: 0.9970
Epoch 130/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0631 - accuracy: 0.9939
Epoch 131/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0522 - accuracy: 1.0000
Epoch 132/500
4/4 [==============================] - 0s 11ms/step - loss: 0.0513 - accuracy: 1.0000
Epoch 133/500
4/4 [==============================] - 0s 13ms/step - loss: 0.0539 - accuracy: 0.9970
Epoch 134/500
4/4 [==============================] - 0s 13ms/step - loss: 0.0544 - accuracy: 0.9939
Epoch 135/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0444 - accuracy: 1.0000
Epoch 136/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0435 - accuracy: 1.0000
Epoch 137/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0447 - accuracy: 0.9970
Epoch 138/500
4/4 [==============================] - 0s 13ms/step - loss: 0.0397 - accuracy: 1.0000
Epoch 139/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0421 - accuracy: 1.0000
Epoch 140/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0375 - accuracy: 0.9970
Epoch 141/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0347 - accuracy: 1.0000
Epoch 142/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0316 - accuracy: 1.0000
Epoch 143/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0292 - accuracy: 1.0000
Epoch 144/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0315 - accuracy: 1.0000
Epoch 145/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0309 - accuracy: 1.0000
Epoch 146/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0341 - accuracy: 0.9970
Epoch 147/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0273 - accuracy: 0.9970
Epoch 148/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0251 - accuracy: 1.0000
Epoch 149/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0209 - accuracy: 1.0000
Epoch 150/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0240 - accuracy: 1.0000
Epoch 151/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0234 - accuracy: 1.0000
Epoch 152/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0204 - accuracy: 1.0000
Epoch 153/500
4/4 [==============================] - 0s 13ms/step - loss: 0.0171 - accuracy: 1.0000
Epoch 154/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0204 - accuracy: 1.0000
Epoch 155/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0207 - accuracy: 1.0000
Epoch 156/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0156 - accuracy: 1.0000
Epoch 157/500
4/4 [==============================] - 0s 11ms/step - loss: 0.0157 - accuracy: 1.0000
Epoch 158/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0146 - accuracy: 1.0000
Epoch 159/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0132 - accuracy: 1.0000
Epoch 160/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0138 - accuracy: 1.0000
Epoch 161/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0135 - accuracy: 1.0000
Epoch 162/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0109 - accuracy: 1.0000
Epoch 163/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0107 - accuracy: 1.0000
Epoch 164/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0093 - accuracy: 1.0000
Epoch 165/500

4/4 [==============================] - 0s 10ms/step - loss: 0.0111 - accuracy: 1.0000
Epoch 166/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0106 - accuracy: 1.0000
Epoch 167/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0104 - accuracy: 1.0000
Epoch 168/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0082 - accuracy: 1.0000
Epoch 169/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0076 - accuracy: 1.0000
Epoch 170/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0109 - accuracy: 0.9970
Epoch 171/500
4/4 [==============================] - 0s 7ms/step - loss: 0.0066 - accuracy: 1.0000
Epoch 172/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0114 - accuracy: 0.9970
Epoch 173/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0055 - accuracy: 1.0000
Epoch 174/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0051 - accuracy: 1.0000
Epoch 175/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0050 - accuracy: 1.0000
Epoch 176/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 177/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0043 - accuracy: 1.0000
Epoch 178/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 179/500
4/4 [==============================] - 0s 13ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 180/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 181/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0039 - accuracy: 1.0000
Epoch 182/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 183/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 184/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0033 - accuracy: 1.0000
Epoch 185/500
4/4 [==============================] - 0s 7ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 186/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0030 - accuracy: 1.0000
Epoch 187/500
4/4 [==============================] - 0s 7ms/step - loss: 0.0029 - accuracy: 1.0000
Epoch 188/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0023 - accuracy: 1.0000
Epoch 189/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 190/500
4/4 [==============================] - 0s 8ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 191/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0058 - accuracy: 0.9970
Epoch 192/500
4/4 [==============================] - 0s 11ms/step - loss: 0.0034 - accuracy: 1.0000
Epoch 193/500
4/4 [==============================] - 0s 13ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 194/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 195/500
4/4 [==============================] - 0s 11ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 196/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 197/500
4/4 [==============================] - 0s 14ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 198/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 199/500
4/4 [==============================] - 0s 12ms/step - loss: 0.0056 - accuracy: 0.9970
Epoch 200/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0033 - accuracy: 0.9970
Epoch 201/500
4/4 [==============================] - 0s 13ms/step - loss: 9.4759e-04 - accuracy: 1.0000
Epoch 202/500
4/4 [==============================] - 0s 10ms/step - loss: 8.7942e-04 - accuracy: 1.0000
Epoch 203/500
4/4 [==============================] - 0s 11ms/step - loss: 8.3889e-04 - accuracy: 1.0000
Epoch 204/500
4/4 [==============================] - 0s 10ms/step - loss: 7.8854e-04 - accuracy: 1.0000
Epoch 205/500
4/4 [==============================] - 0s 9ms/step - loss: 7.8100e-04 - accuracy: 1.0000
Epoch 206/500
4/4 [==============================] - 0s 10ms/step - loss: 7.3424e-04 - accuracy: 1.0000
Epoch 207/500
4/4 [==============================] - 0s 12ms/step - loss: 6.7181e-04 - accuracy: 1.0000
Epoch 208/500
4/4 [==============================] - 0s 11ms/step - loss: 6.2017e-04 - accuracy: 1.0000
Epoch 209/500
4/4 [==============================] - 0s 8ms/step - loss: 6.1873e-04 - accuracy: 1.0000
Epoch 210/500
4/4 [==============================] - 0s 10ms/step - loss: 6.2598e-04 - accuracy: 1.0000
Epoch 211/500
4/4 [==============================] - 0s 14ms/step - loss: 5.2148e-04 - accuracy: 1.0000
Epoch 212/500
4/4 [==============================] - 0s 10ms/step - loss: 4.9194e-04 - accuracy: 1.0000
Epoch 213/500
4/4 [==============================] - 0s 10ms/step - loss: 4.7845e-04 - accuracy: 1.0000
Epoch 214/500
4/4 [==============================] - 0s 10ms/step - loss: 5.1536e-04 - accuracy: 1.0000
Epoch 215/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0025 - accuracy: 1.0000
Epoch 216/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 217/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0042 - accuracy: 0.9970
Epoch 218/500
4/4 [==============================] - 0s 9ms/step - loss: 0.0068 - accuracy: 0.9970
Epoch 219/500
4/4 [==============================] - 0s 10ms/step - loss: 7.7234e-04 - accuracy: 1.0000
Epoch 220/500
4/4 [==============================] - 0s 11ms/step - loss: 4.7685e-04 - accuracy: 1.0000
Epoch 221/500
4/4 [==============================] - 0s 16ms/step - loss: 4.2105e-04 - accuracy: 1.0000
Epoch 222/500
4/4 [==============================] - 0s 11ms/step - loss: 3.8329e-04 - accuracy: 1.0000
Epoch 223/500
4/4 [==============================] - 0s 10ms/step - loss: 3.4916e-04 - accuracy: 1.0000
Epoch 224/500
4/4 [==============================] - 0s 10ms/step - loss: 3.2453e-04 - accuracy: 1.0000
Epoch 225/500
4/4 [==============================] - 0s 10ms/step - loss: 3.0305e-04 - accuracy: 1.0000
Epoch 226/500
4/4 [==============================] - 0s 10ms/step - loss: 2.8363e-04 - accuracy: 1.0000
Epoch 227/500
4/4 [==============================] - 0s 10ms/step - loss: 2.6317e-04 - accuracy: 1.0000
Epoch 228/500
4/4 [==============================] - 0s 9ms/step - loss: 2.5080e-04 - accuracy: 1.0000
Epoch 229/500
4/4 [==============================] - 0s 9ms/step - loss: 2.3600e-04 - accuracy: 1.0000
Epoch 230/500
4/4 [==============================] - 0s 11ms/step - loss: 2.2164e-04 - accuracy: 1.0000
Epoch 231/500
4/4 [==============================] - 0s 12ms/step - loss: 1.9862e-04 - accuracy: 1.0000
Epoch 232/500
4/4 [==============================] - 0s 13ms/step - loss: 1.8893e-04 - accuracy: 1.0000
Epoch 233/500
4/4 [==============================] - 0s 11ms/step - loss: 1.8019e-04 - accuracy: 1.0000
Epoch 234/500
4/4 [==============================] - 0s 10ms/step - loss: 1.6854e-04 - accuracy: 1.0000
Epoch 235/500
4/4 [==============================] - 0s 11ms/step - loss: 1.5676e-04 - accuracy: 1.0000
Epoch 236/500
4/4 [==============================] - 0s 11ms/step - loss: 1.5176e-04 - accuracy: 1.0000
Epoch 237/500
4/4 [==============================] - 0s 10ms/step - loss: 1.4193e-04 - accuracy: 1.0000
Epoch 238/500
4/4 [==============================] - 0s 10ms/step - loss: 1.3154e-04 - accuracy: 1.0000
Epoch 239/500
4/4 [==============================] - 0s 10ms/step - loss: 1.2202e-04 - accuracy: 1.0000
Epoch 240/500
4/4 [==============================] - 0s 11ms/step - loss: 1.1621e-04 - accuracy: 1.0000
Epoch 241/500
4/4 [==============================] - 0s 12ms/step - loss: 1.2218e-04 - accuracy: 1.0000
Epoch 242/500
4/4 [==============================] - 0s 11ms/step - loss: 1.2756e-04 - accuracy: 1.0000
Epoch 243/500
4/4 [==============================] - 0s 11ms/step - loss: 9.9565e-05 - accuracy: 1.0000
Epoch 244/500
4/4 [==============================] - 0s 13ms/step - loss: 8.6027e-05 - accuracy: 1.0000
Epoch 245/500

4/4 [==============================] - 0s 11ms/step - loss: 8.0741e-05 - accuracy: 1.0000
Epoch 246/500
4/4 [==============================] - 0s 13ms/step - loss: 7.7679e-05 - accuracy: 1.0000
Epoch 247/500
4/4 [==============================] - 0s 8ms/step - loss: 9.1025e-05 - accuracy: 1.0000
Epoch 248/500
4/4 [==============================] - 0s 13ms/step - loss: 1.4026e-04 - accuracy: 1.0000
Epoch 249/500
4/4 [==============================] - 0s 10ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 250/500
4/4 [==============================] - 0s 10ms/step - loss: 3.5297e-04 - accuracy: 1.0000
Epoch 251/500
4/4 [==============================] - 0s 15ms/step - loss: 5.9860e-05 - accuracy: 1.0000
Epoch 252/500
4/4 [==============================] - 0s 10ms/step - loss: 5.5991e-05 - accuracy: 1.0000
Epoch 253/500
4/4 [==============================] - 0s 8ms/step - loss: 5.2874e-05 - accuracy: 1.0000
Epoch 254/500
4/4 [==============================] - 0s 10ms/step - loss: 4.9991e-05 - accuracy: 1.0000
Epoch 255/500
4/4 [==============================] - 0s 8ms/step - loss: 4.7987e-05 - accuracy: 1.0000
Epoch 256/500
4/4 [==============================] - 0s 10ms/step - loss: 4.5512e-05 - accuracy: 1.0000
Epoch 257/500
4/4 [==============================] - 0s 9ms/step - loss: 4.3750e-05 - accuracy: 1.0000
Epoch 258/500
4/4 [==============================] - 0s 9ms/step - loss: 4.1080e-05 - accuracy: 1.0000
Epoch 259/500
4/4 [==============================] - 0s 10ms/step - loss: 3.8395e-05 - accuracy: 1.0000
Epoch 260/500
4/4 [==============================] - 0s 10ms/step - loss: 3.7011e-05 - accuracy: 1.0000
Epoch 261/500
4/4 [==============================] - 0s 10ms/step - loss: 3.5658e-05 - accuracy: 1.0000
Epoch 262/500
4/4 [==============================] - 0s 8ms/step - loss: 3.4292e-05 - accuracy: 1.0000
Epoch 263/500
4/4 [==============================] - 0s 10ms/step - loss: 3.1095e-05 - accuracy: 1.0000
Epoch 264/500
4/4 [==============================] - 0s 8ms/step - loss: 3.0946e-05 - accuracy: 1.0000
Epoch 265/500
4/4 [==============================] - 0s 10ms/step - loss: 4.3750e-04 - accuracy: 1.0000
Epoch 266/500
4/4 [==============================] - 0s 7ms/step - loss: 4.9322e-04 - accuracy: 1.0000
Epoch 267/500
4/4 [==============================] - 0s 10ms/step - loss: 4.6880e-05 - accuracy: 1.0000
Epoch 268/500
4/4 [==============================] - 0s 9ms/step - loss: 3.3026e-05 - accuracy: 1.0000
Epoch 269/500
4/4 [==============================] - 0s 11ms/step - loss: 2.9132e-05 - accuracy: 1.0000
Epoch 270/500
4/4 [==============================] - 0s 12ms/step - loss: 2.6703e-05 - accuracy: 1.0000
Epoch 271/500
4/4 [==============================] - 0s 11ms/step - loss: 2.4619e-05 - accuracy: 1.0000
Epoch 272/500
4/4 [==============================] - 0s 10ms/step - loss: 2.2900e-05 - accuracy: 1.0000
Epoch 273/500
4/4 [==============================] - 0s 12ms/step - loss: 2.1259e-05 - accuracy: 1.0000
Epoch 274/500
4/4 [==============================] - 0s 11ms/step - loss: 1.9779e-05 - accuracy: 1.0000
Epoch 275/500
4/4 [==============================] - 0s 10ms/step - loss: 1.8668e-05 - accuracy: 1.0000
Epoch 276/500
4/4 [==============================] - 0s 9ms/step - loss: 1.7759e-05 - accuracy: 1.0000
Epoch 277/500
4/4 [==============================] - 0s 12ms/step - loss: 1.6603e-05 - accuracy: 1.0000
Epoch 278/500
4/4 [==============================] - 0s 10ms/step - loss: 1.5949e-05 - accuracy: 1.0000
Epoch 279/500
4/4 [==============================] - 0s 9ms/step - loss: 1.5074e-05 - accuracy: 1.0000
Epoch 280/500
4/4 [==============================] - 0s 8ms/step - loss: 1.4378e-05 - accuracy: 1.0000
Epoch 281/500
4/4 [==============================] - 0s 11ms/step - loss: 1.3742e-05 - accuracy: 1.0000
Epoch 282/500
4/4 [==============================] - 0s 11ms/step - loss: 1.3108e-05 - accuracy: 1.0000
Epoch 283/500
4/4 [==============================] - 0s 10ms/step - loss: 1.9580e-05 - accuracy: 1.0000
Epoch 284/500
4/4 [==============================] - 0s 6ms/step - loss: 1.9917e-05 - accuracy: 1.0000
Epoch 285/500
4/4 [==============================] - 0s 14ms/step - loss: 1.1453e-05 - accuracy: 1.0000
Epoch 286/500
4/4 [==============================] - 0s 11ms/step - loss: 1.0762e-05 - accuracy: 1.0000
Epoch 287/500
4/4 [==============================] - 0s 11ms/step - loss: 1.0077e-05 - accuracy: 1.0000
Epoch 288/500
4/4 [==============================] - 0s 11ms/step - loss: 9.6847e-06 - accuracy: 1.0000
Epoch 289/500
4/4 [==============================] - 0s 10ms/step - loss: 9.3329e-06 - accuracy: 1.0000
Epoch 290/500
4/4 [==============================] - 0s 11ms/step - loss: 9.0609e-06 - accuracy: 1.0000
Epoch 291/500
4/4 [==============================] - 0s 11ms/step - loss: 8.7412e-06 - accuracy: 1.0000
Epoch 292/500
4/4 [==============================] - 0s 9ms/step - loss: 8.1907e-06 - accuracy: 1.0000
Epoch 293/500
4/4 [==============================] - 0s 10ms/step - loss: 7.9873e-06 - accuracy: 1.0000
Epoch 294/500
4/4 [==============================] - 0s 11ms/step - loss: 7.4870e-06 - accuracy: 1.0000
Epoch 295/500
4/4 [==============================] - 0s 10ms/step - loss: 8.5869e-06 - accuracy: 1.0000
Epoch 296/500
4/4 [==============================] - 0s 10ms/step - loss: 7.5191e-06 - accuracy: 1.0000
Epoch 297/500
4/4 [==============================] - 0s 10ms/step - loss: 6.9014e-06 - accuracy: 1.0000
Epoch 298/500
4/4 [==============================] - 0s 10ms/step - loss: 7.4548e-06 - accuracy: 1.0000
Epoch 299/500
4/4 [==============================] - 0s 10ms/step - loss: 7.0592e-06 - accuracy: 1.0000
Epoch 300/500
4/4 [==============================] - 0s 11ms/step - loss: 4.1607e-04 - accuracy: 1.0000
Epoch 301/500
4/4 [==============================] - 0s 10ms/step - loss: 4.4803e-05 - accuracy: 1.0000
Epoch 302/500
4/4 [==============================] - 0s 10ms/step - loss: 5.7411e-06 - accuracy: 1.0000
Epoch 303/500
4/4 [==============================] - 0s 10ms/step - loss: 5.5092e-06 - accuracy: 1.0000
Epoch 304/500
4/4 [==============================] - 0s 11ms/step - loss: 5.3030e-06 - accuracy: 1.0000
Epoch 305/500
4/4 [==============================] - 0s 15ms/step - loss: 5.1484e-06 - accuracy: 1.0000
Epoch 306/500
4/4 [==============================] - 0s 11ms/step - loss: 4.9916e-06 - accuracy: 1.0000
Epoch 307/500
4/4 [==============================] - 0s 10ms/step - loss: 4.8370e-06 - accuracy: 1.0000
Epoch 308/500
4/4 [==============================] - 0s 11ms/step - loss: 4.6983e-06 - accuracy: 1.0000
Epoch 309/500
4/4 [==============================] - 0s 9ms/step - loss: 4.5527e-06 - accuracy: 1.0000
Epoch 310/500
4/4 [==============================] - 0s 11ms/step - loss: 4.4299e-06 - accuracy: 1.0000
Epoch 311/500
4/4 [==============================] - 0s 11ms/step - loss: 4.3125e-06 - accuracy: 1.0000
Epoch 312/500
4/4 [==============================] - 0s 13ms/step - loss: 4.1420e-06 - accuracy: 1.0000
Epoch 313/500
4/4 [==============================] - 0s 10ms/step - loss: 4.0542e-06 - accuracy: 1.0000
Epoch 314/500
4/4 [==============================] - 0s 8ms/step - loss: 3.9400e-06 - accuracy: 1.0000
Epoch 315/500
4/4 [==============================] - 0s 10ms/step - loss: 3.8010e-06 - accuracy: 1.0000
Epoch 316/500
4/4 [==============================] - 0s 12ms/step - loss: 3.6742e-06 - accuracy: 1.0000
Epoch 317/500
4/4 [==============================] - 0s 5ms/step - loss: 3.5846e-06 - accuracy: 1.0000
Epoch 318/500
4/4 [==============================] - 0s 10ms/step - loss: 3.4939e-06 - accuracy: 1.0000
Epoch 319/500
4/4 [==============================] - 0s 10ms/step - loss: 3.4390e-06 - accuracy: 1.0000
Epoch 320/500
4/4 [==============================] - 0s 9ms/step - loss: 3.3039e-06 - accuracy: 1.0000
Epoch 321/500
4/4 [==============================] - 0s 11ms/step - loss: 3.2212e-06 - accuracy: 1.0000
Epoch 322/500
4/4 [==============================] - 0s 9ms/step - loss: 3.1381e-06 - accuracy: 1.0000
Epoch 323/500
4/4 [==============================] - 0s 10ms/step - loss: 3.0290e-06 - accuracy: 1.0000
Epoch 324/500

4/4 [==============================] - 0s 15ms/step - loss: 2.9423e-06 - accuracy: 1.0000
Epoch 325/500
4/4 [==============================] - 0s 8ms/step - loss: 2.8989e-06 - accuracy: 1.0000
Epoch 326/500
4/4 [==============================] - 0s 9ms/step - loss: 2.8184e-06 - accuracy: 1.0000
Epoch 327/500
4/4 [==============================] - 0s 10ms/step - loss: 2.7436e-06 - accuracy: 1.0000
Epoch 328/500
4/4 [==============================] - 0s 11ms/step - loss: 2.7057e-06 - accuracy: 1.0000
Epoch 329/500
4/4 [==============================] - 0s 11ms/step - loss: 2.5991e-06 - accuracy: 1.0000
Epoch 330/500
4/4 [==============================] - 0s 10ms/step - loss: 2.5251e-06 - accuracy: 1.0000
Epoch 331/500
4/4 [==============================] - 0s 11ms/step - loss: 2.5168e-06 - accuracy: 1.0000
Epoch 332/500
4/4 [==============================] - 0s 9ms/step - loss: 2.5410e-06 - accuracy: 1.0000
Epoch 333/500
4/4 [==============================] - 0s 11ms/step - loss: 2.3708e-06 - accuracy: 1.0000
Epoch 334/500
4/4 [==============================] - 0s 8ms/step - loss: 2.2881e-06 - accuracy: 1.0000
Epoch 335/500
4/4 [==============================] - 0s 10ms/step - loss: 2.3098e-06 - accuracy: 1.0000
Epoch 336/500
4/4 [==============================] - 0s 10ms/step - loss: 2.2238e-06 - accuracy: 1.0000
Epoch 337/500
4/4 [==============================] - 0s 10ms/step - loss: 2.0937e-06 - accuracy: 1.0000
Epoch 338/500
4/4 [==============================] - 0s 10ms/step - loss: 2.1580e-06 - accuracy: 1.0000
Epoch 339/500
4/4 [==============================] - 0s 8ms/step - loss: 2.0135e-06 - accuracy: 1.0000
Epoch 340/500
4/4 [==============================] - 0s 9ms/step - loss: 2.0630e-06 - accuracy: 1.0000
Epoch 341/500
4/4 [==============================] - 0s 10ms/step - loss: 1.9633e-06 - accuracy: 1.0000
Epoch 342/500
4/4 [==============================] - 0s 13ms/step - loss: 1.9326e-06 - accuracy: 1.0000
Epoch 343/500
4/4 [==============================] - 0s 10ms/step - loss: 1.9023e-06 - accuracy: 1.0000
Epoch 344/500
4/4 [==============================] - 0s 8ms/step - loss: 1.7950e-06 - accuracy: 1.0000
Epoch 345/500
4/4 [==============================] - 0s 9ms/step - loss: 1.7701e-06 - accuracy: 1.0000
Epoch 346/500
4/4 [==============================] - 0s 10ms/step - loss: 1.7610e-06 - accuracy: 1.0000
Epoch 347/500
4/4 [==============================] - 0s 10ms/step - loss: 1.7018e-06 - accuracy: 1.0000
Epoch 348/500
4/4 [==============================] - 0s 10ms/step - loss: 1.7881e-06 - accuracy: 1.0000
Epoch 349/500
4/4 [==============================] - 0s 10ms/step - loss: 1.6740e-06 - accuracy: 1.0000
Epoch 350/500
4/4 [==============================] - 0s 10ms/step - loss: 1.5988e-06 - accuracy: 1.0000
Epoch 351/500
4/4 [==============================] - 0s 10ms/step - loss: 1.5483e-06 - accuracy: 1.0000
Epoch 352/500
4/4 [==============================] - 0s 8ms/step - loss: 1.5259e-06 - accuracy: 1.0000
Epoch 353/500
4/4 [==============================] - 0s 10ms/step - loss: 1.5006e-06 - accuracy: 1.0000
Epoch 354/500
4/4 [==============================] - 0s 10ms/step - loss: 1.4572e-06 - accuracy: 1.0000
Epoch 355/500
4/4 [==============================] - 0s 11ms/step - loss: 1.4298e-06 - accuracy: 1.0000
Epoch 356/500
4/4 [==============================] - 0s 8ms/step - loss: 1.3994e-06 - accuracy: 1.0000
Epoch 357/500
4/4 [==============================] - 0s 10ms/step - loss: 1.4099e-06 - accuracy: 1.0000
Epoch 358/500
4/4 [==============================] - 0s 11ms/step - loss: 1.3789e-06 - accuracy: 1.0000
Epoch 359/500
4/4 [==============================] - 0s 11ms/step - loss: 1.3969e-06 - accuracy: 1.0000
Epoch 360/500
4/4 [==============================] - 0s 13ms/step - loss: 1.3463e-06 - accuracy: 1.0000
Epoch 361/500
4/4 [==============================] - 0s 10ms/step - loss: 1.2647e-06 - accuracy: 1.0000
Epoch 362/500
4/4 [==============================] - 0s 11ms/step - loss: 1.2463e-06 - accuracy: 1.0000
Epoch 363/500
4/4 [==============================] - 0s 10ms/step - loss: 1.2250e-06 - accuracy: 1.0000
Epoch 364/500
4/4 [==============================] - 0s 14ms/step - loss: 1.2094e-06 - accuracy: 1.0000
Epoch 365/500
4/4 [==============================] - 0s 11ms/step - loss: 1.1964e-06 - accuracy: 1.0000
Epoch 366/500
4/4 [==============================] - 0s 10ms/step - loss: 1.1751e-06 - accuracy: 1.0000
Epoch 367/500
4/4 [==============================] - 0s 10ms/step - loss: 1.1524e-06 - accuracy: 1.0000
Epoch 368/500
4/4 [==============================] - 0s 11ms/step - loss: 1.1412e-06 - accuracy: 1.0000
Epoch 369/500
4/4 [==============================] - 0s 13ms/step - loss: 1.1285e-06 - accuracy: 1.0000
Epoch 370/500
4/4 [==============================] - 0s 12ms/step - loss: 1.0985e-06 - accuracy: 1.0000
Epoch 371/500
4/4 [==============================] - 0s 10ms/step - loss: 1.0938e-06 - accuracy: 1.0000
Epoch 372/500
4/4 [==============================] - 0s 9ms/step - loss: 1.0902e-06 - accuracy: 1.0000
Epoch 373/500
4/4 [==============================] - 0s 14ms/step - loss: 1.0628e-06 - accuracy: 1.0000
Epoch 374/500
4/4 [==============================] - 0s 10ms/step - loss: 1.0400e-06 - accuracy: 1.0000
Epoch 375/500
4/4 [==============================] - 0s 9ms/step - loss: 1.0158e-06 - accuracy: 1.0000
Epoch 376/500
4/4 [==============================] - 0s 11ms/step - loss: 1.0035e-06 - accuracy: 1.0000
Epoch 377/500
4/4 [==============================] - 0s 9ms/step - loss: 9.8619e-07 - accuracy: 1.0000
Epoch 378/500
4/4 [==============================] - 0s 11ms/step - loss: 9.8799e-07 - accuracy: 1.0000
Epoch 379/500
4/4 [==============================] - 0s 10ms/step - loss: 9.5548e-07 - accuracy: 1.0000
Epoch 380/500
4/4 [==============================] - 0s 8ms/step - loss: 9.6162e-07 - accuracy: 1.0000
Epoch 381/500
4/4 [==============================] - 0s 10ms/step - loss: 9.4284e-07 - accuracy: 1.0000
Epoch 382/500
4/4 [==============================] - 0s 11ms/step - loss: 9.2514e-07 - accuracy: 1.0000
Epoch 383/500
4/4 [==============================] - 0s 10ms/step - loss: 9.2152e-07 - accuracy: 1.0000
Epoch 384/500
4/4 [==============================] - 0s 8ms/step - loss: 9.0527e-07 - accuracy: 1.0000
Epoch 385/500
4/4 [==============================] - 0s 10ms/step - loss: 9.0743e-07 - accuracy: 1.0000
Epoch 386/500
4/4 [==============================] - 0s 10ms/step - loss: 8.8323e-07 - accuracy: 1.0000
Epoch 387/500
4/4 [==============================] - 0s 11ms/step - loss: 8.7673e-07 - accuracy: 1.0000
Epoch 388/500
4/4 [==============================] - 0s 9ms/step - loss: 8.6120e-07 - accuracy: 1.0000
Epoch 389/500
4/4 [==============================] - 0s 11ms/step - loss: 8.5722e-07 - accuracy: 1.0000
Epoch 390/500
4/4 [==============================] - 0s 8ms/step - loss: 8.4169e-07 - accuracy: 1.0000
Epoch 391/500
4/4 [==============================] - 0s 12ms/step - loss: 8.3735e-07 - accuracy: 1.0000
Epoch 392/500
4/4 [==============================] - 0s 10ms/step - loss: 8.2182e-07 - accuracy: 1.0000
Epoch 393/500
4/4 [==============================] - 0s 10ms/step - loss: 8.1135e-07 - accuracy: 1.0000
Epoch 394/500
4/4 [==============================] - 0s 9ms/step - loss: 8.0195e-07 - accuracy: 1.0000
Epoch 395/500
4/4 [==============================] - 0s 8ms/step - loss: 7.9545e-07 - accuracy: 1.0000
Epoch 396/500
4/4 [==============================] - 0s 10ms/step - loss: 7.8931e-07 - accuracy: 1.0000
Epoch 397/500
4/4 [==============================] - 0s 11ms/step - loss: 7.7956e-07 - accuracy: 1.0000
Epoch 398/500
4/4 [==============================] - 0s 11ms/step - loss: 7.6402e-07 - accuracy: 1.0000
Epoch 399/500
4/4 [==============================] - 0s 12ms/step - loss: 7.5824e-07 - accuracy: 1.0000
Epoch 400/500
4/4 [==============================] - 0s 12ms/step - loss: 7.5824e-07 - accuracy: 1.0000
Epoch 401/500
4/4 [==============================] - 0s 6ms/step - loss: 7.4379e-07 - accuracy: 1.0000
Epoch 402/500
4/4 [==============================] - 0s 13ms/step - loss: 7.3151e-07 - accuracy: 1.0000
Epoch 403/500

4/4 [==============================] - 0s 10ms/step - loss: 7.2609e-07 - accuracy: 1.0000
Epoch 404/500
4/4 [==============================] - 0s 11ms/step - loss: 7.2429e-07 - accuracy: 1.0000
Epoch 405/500
4/4 [==============================] - 0s 8ms/step - loss: 7.2104e-07 - accuracy: 1.0000
Epoch 406/500
4/4 [==============================] - 0s 9ms/step - loss: 7.0622e-07 - accuracy: 1.0000
Epoch 407/500
4/4 [==============================] - 0s 12ms/step - loss: 6.9755e-07 - accuracy: 1.0000
Epoch 408/500
4/4 [==============================] - 0s 10ms/step - loss: 6.8888e-07 - accuracy: 1.0000
Epoch 409/500
4/4 [==============================] - 0s 9ms/step - loss: 6.8925e-07 - accuracy: 1.0000
Epoch 410/500
4/4 [==============================] - 0s 10ms/step - loss: 6.8274e-07 - accuracy: 1.0000
Epoch 411/500
4/4 [==============================] - 0s 9ms/step - loss: 6.6721e-07 - accuracy: 1.0000
Epoch 412/500
4/4 [==============================] - 0s 10ms/step - loss: 6.6577e-07 - accuracy: 1.0000
Epoch 413/500
4/4 [==============================] - 0s 9ms/step - loss: 6.6757e-07 - accuracy: 1.0000
Epoch 414/500
4/4 [==============================] - 0s 15ms/step - loss: 6.5710e-07 - accuracy: 1.0000
Epoch 415/500
4/4 [==============================] - 0s 11ms/step - loss: 6.5529e-07 - accuracy: 1.0000
Epoch 416/500
4/4 [==============================] - 0s 8ms/step - loss: 6.4265e-07 - accuracy: 1.0000
Epoch 417/500
4/4 [==============================] - 0s 10ms/step - loss: 6.4337e-07 - accuracy: 1.0000
Epoch 418/500
4/4 [==============================] - 0s 10ms/step - loss: 6.3181e-07 - accuracy: 1.0000
Epoch 419/500
4/4 [==============================] - 0s 10ms/step - loss: 6.2928e-07 - accuracy: 1.0000
Epoch 420/500
4/4 [==============================] - 0s 11ms/step - loss: 6.1519e-07 - accuracy: 1.0000
Epoch 421/500
4/4 [==============================] - 0s 11ms/step - loss: 6.1266e-07 - accuracy: 1.0000
Epoch 422/500
4/4 [==============================] - 0s 10ms/step - loss: 6.0941e-07 - accuracy: 1.0000
Epoch 423/500
4/4 [==============================] - 0s 11ms/step - loss: 6.0399e-07 - accuracy: 1.0000
Epoch 424/500
4/4 [==============================] - 0s 11ms/step - loss: 5.9713e-07 - accuracy: 1.0000
Epoch 425/500
4/4 [==============================] - 0s 11ms/step - loss: 5.9063e-07 - accuracy: 1.0000
Epoch 426/500
4/4 [==============================] - 0s 11ms/step - loss: 5.8846e-07 - accuracy: 1.0000
Epoch 427/500
4/4 [==============================] - 0s 9ms/step - loss: 5.7907e-07 - accuracy: 1.0000
Epoch 428/500
4/4 [==============================] - 0s 10ms/step - loss: 5.7509e-07 - accuracy: 1.0000
Epoch 429/500
4/4 [==============================] - 0s 8ms/step - loss: 5.7509e-07 - accuracy: 1.0000
Epoch 430/500
4/4 [==============================] - 0s 10ms/step - loss: 5.7076e-07 - accuracy: 1.0000
Epoch 431/500
4/4 [==============================] - 0s 10ms/step - loss: 5.6534e-07 - accuracy: 1.0000
Epoch 432/500
4/4 [==============================] - 0s 11ms/step - loss: 5.5270e-07 - accuracy: 1.0000
Epoch 433/500
4/4 [==============================] - 0s 10ms/step - loss: 5.4728e-07 - accuracy: 1.0000
Epoch 434/500
4/4 [==============================] - 0s 10ms/step - loss: 5.4836e-07 - accuracy: 1.0000
Epoch 435/500
4/4 [==============================] - 0s 11ms/step - loss: 5.4331e-07 - accuracy: 1.0000
Epoch 436/500
4/4 [==============================] - 0s 11ms/step - loss: 5.3825e-07 - accuracy: 1.0000
Epoch 437/500
4/4 [==============================] - 0s 10ms/step - loss: 5.3138e-07 - accuracy: 1.0000
Epoch 438/500
4/4 [==============================] - 0s 11ms/step - loss: 5.3102e-07 - accuracy: 1.0000
Epoch 439/500
4/4 [==============================] - 0s 10ms/step - loss: 5.2199e-07 - accuracy: 1.0000
Epoch 440/500
4/4 [==============================] - 0s 10ms/step - loss: 5.1874e-07 - accuracy: 1.0000
Epoch 441/500
4/4 [==============================] - 0s 10ms/step - loss: 5.1730e-07 - accuracy: 1.0000
Epoch 442/500
4/4 [==============================] - 0s 10ms/step - loss: 5.1874e-07 - accuracy: 1.0000
Epoch 443/500
4/4 [==============================] - 0s 12ms/step - loss: 5.1441e-07 - accuracy: 1.0000
Epoch 444/500
4/4 [==============================] - 0s 11ms/step - loss: 5.1079e-07 - accuracy: 1.0000
Epoch 445/500
4/4 [==============================] - 0s 11ms/step - loss: 5.0176e-07 - accuracy: 1.0000
Epoch 446/500
4/4 [==============================] - 0s 15ms/step - loss: 4.9851e-07 - accuracy: 1.0000
Epoch 447/500
4/4 [==============================] - 0s 12ms/step - loss: 5.0068e-07 - accuracy: 1.0000
Epoch 448/500
4/4 [==============================] - 0s 13ms/step - loss: 4.9526e-07 - accuracy: 1.0000
Epoch 449/500
4/4 [==============================] - 0s 12ms/step - loss: 4.9056e-07 - accuracy: 1.0000
Epoch 450/500
4/4 [==============================] - 0s 10ms/step - loss: 4.8695e-07 - accuracy: 1.0000
Epoch 451/500
4/4 [==============================] - 0s 10ms/step - loss: 4.8587e-07 - accuracy: 1.0000
Epoch 452/500
4/4 [==============================] - 0s 10ms/step - loss: 4.7900e-07 - accuracy: 1.0000
Epoch 453/500
4/4 [==============================] - 0s 10ms/step - loss: 4.7467e-07 - accuracy: 1.0000
Epoch 454/500
4/4 [==============================] - 0s 10ms/step - loss: 4.7142e-07 - accuracy: 1.0000
Epoch 455/500
4/4 [==============================] - 0s 11ms/step - loss: 4.7106e-07 - accuracy: 1.0000
Epoch 456/500
4/4 [==============================] - 0s 9ms/step - loss: 4.6744e-07 - accuracy: 1.0000
Epoch 457/500
4/4 [==============================] - 0s 7ms/step - loss: 4.6130e-07 - accuracy: 1.0000
Epoch 458/500
4/4 [==============================] - 0s 10ms/step - loss: 4.6239e-07 - accuracy: 1.0000
Epoch 459/500
4/4 [==============================] - 0s 10ms/step - loss: 4.5083e-07 - accuracy: 1.0000
Epoch 460/500
4/4 [==============================] - 0s 11ms/step - loss: 4.5589e-07 - accuracy: 1.0000
Epoch 461/500
4/4 [==============================] - 0s 8ms/step - loss: 4.4902e-07 - accuracy: 1.0000
Epoch 462/500
4/4 [==============================] - 0s 9ms/step - loss: 4.5011e-07 - accuracy: 1.0000
Epoch 463/500
4/4 [==============================] - 0s 10ms/step - loss: 4.5011e-07 - accuracy: 1.0000
Epoch 464/500
4/4 [==============================] - 0s 11ms/step - loss: 4.3891e-07 - accuracy: 1.0000
Epoch 465/500
4/4 [==============================] - 0s 10ms/step - loss: 4.3602e-07 - accuracy: 1.0000
Epoch 466/500
4/4 [==============================] - 0s 8ms/step - loss: 4.3457e-07 - accuracy: 1.0000
Epoch 467/500
4/4 [==============================] - 0s 12ms/step - loss: 4.3240e-07 - accuracy: 1.0000
Epoch 468/500
4/4 [==============================] - 0s 19ms/step - loss: 4.2843e-07 - accuracy: 1.0000
Epoch 469/500
4/4 [==============================] - 0s 12ms/step - loss: 4.2590e-07 - accuracy: 1.0000
Epoch 470/500
4/4 [==============================] - 0s 11ms/step - loss: 4.2229e-07 - accuracy: 1.0000
Epoch 471/500
4/4 [==============================] - 0s 11ms/step - loss: 4.2482e-07 - accuracy: 1.0000
Epoch 472/500
4/4 [==============================] - 0s 10ms/step - loss: 4.2373e-07 - accuracy: 1.0000
Epoch 473/500
4/4 [==============================] - 0s 11ms/step - loss: 4.1615e-07 - accuracy: 1.0000
Epoch 474/500
4/4 [==============================] - 0s 11ms/step - loss: 4.1615e-07 - accuracy: 1.0000
Epoch 475/500
4/4 [==============================] - 0s 11ms/step - loss: 4.0892e-07 - accuracy: 1.0000
Epoch 476/500
4/4 [==============================] - 0s 11ms/step - loss: 4.1109e-07 - accuracy: 1.0000
Epoch 477/500
4/4 [==============================] - 0s 11ms/step - loss: 4.0784e-07 - accuracy: 1.0000
Epoch 478/500
4/4 [==============================] - 0s 11ms/step - loss: 4.0170e-07 - accuracy: 1.0000
Epoch 479/500
4/4 [==============================] - 0s 10ms/step - loss: 4.0567e-07 - accuracy: 1.0000
Epoch 480/500
4/4 [==============================] - 0s 10ms/step - loss: 4.0098e-07 - accuracy: 1.0000
Epoch 481/500
4/4 [==============================] - 0s 10ms/step - loss: 3.9773e-07 - accuracy: 1.0000
Epoch 482/500

4/4 [==============================] - 0s 14ms/step - loss: 3.9628e-07 - accuracy: 1.0000
Epoch 483/500
4/4 [==============================] - 0s 11ms/step - loss: 3.9447e-07 - accuracy: 1.0000
Epoch 484/500
4/4 [==============================] - 0s 10ms/step - loss: 3.8653e-07 - accuracy: 1.0000
Epoch 485/500
4/4 [==============================] - 0s 10ms/step - loss: 3.8761e-07 - accuracy: 1.0000
Epoch 486/500
4/4 [==============================] - 0s 10ms/step - loss: 3.8833e-07 - accuracy: 1.0000
Epoch 487/500
4/4 [==============================] - 0s 11ms/step - loss: 3.8400e-07 - accuracy: 1.0000
Epoch 488/500
4/4 [==============================] - 0s 10ms/step - loss: 3.8183e-07 - accuracy: 1.0000
Epoch 489/500
4/4 [==============================] - 0s 7ms/step - loss: 3.8075e-07 - accuracy: 1.0000
Epoch 490/500
4/4 [==============================] - 0s 10ms/step - loss: 3.7677e-07 - accuracy: 1.0000
Epoch 491/500
4/4 [==============================] - 0s 13ms/step - loss: 3.7822e-07 - accuracy: 1.0000
Epoch 492/500
4/4 [==============================] - 0s 11ms/step - loss: 3.7533e-07 - accuracy: 1.0000
Epoch 493/500
4/4 [==============================] - 0s 10ms/step - loss: 3.7605e-07 - accuracy: 1.0000
Epoch 494/500
4/4 [==============================] - 0s 11ms/step - loss: 3.7063e-07 - accuracy: 1.0000
Epoch 495/500
4/4 [==============================] - 0s 11ms/step - loss: 3.6810e-07 - accuracy: 1.0000
Epoch 496/500
4/4 [==============================] - 0s 12ms/step - loss: 3.6702e-07 - accuracy: 1.0000
Epoch 497/500
4/4 [==============================] - 0s 10ms/step - loss: 3.6485e-07 - accuracy: 1.0000
Epoch 498/500
4/4 [==============================] - 0s 9ms/step - loss: 3.6413e-07 - accuracy: 1.0000
Epoch 499/500
4/4 [==============================] - 0s 10ms/step - loss: 3.5691e-07 - accuracy: 1.0000
Epoch 500/500
4/4 [==============================] - 0s 11ms/step - loss: 3.6088e-07 - accuracy: 1.0000
학습시간 : 27.858307123184204

In [18]:
model.evaluate([X_enc,X_dec],Y_dec)

4/4 [==============================] - 1s 7ms/step - loss: 3.5293e-07 - accuracy: 1.0000

[3.529316643380298e-07, 1.0]

## 9. 모델 사용
- 쉬운 문제 : 트레인셋에서 사용한 단어를 그대로 사용
- 문자의 순서를 바꿔서도 예측이 가능한가 체크

In [19]:
# 쉬운 문제 cold, cook, down, cost, copy, duty, date...
easy_test = [['cold','PP'],['cook','PP'],['down','PP'],['cost','PP'],['duty','PP'],['date','PP']]
enc_in, dec_in, dec_out = encoding(easy_test)

In [20]:
# 위의 문제 예측하기
pred = model.predict([np.array(enc_in),np.array(dec_in)])

1/1 [==============================] - 1s 898ms/step

In [21]:
for row,word in zip(pred.argmax(axis=-1).tolist(),easy_test) :
    print(word[0],"=>" ,''.join([alpha[c] for c in row if c not in (0,1,2)]))

cold => 감기
cook => 요리
down => 아래
cost => 비용
duty => 의무
date => 날짜

In [22]:
# 어려운 문제
easy_test = [['clod','PP'],['coko','PP'],['donw','PP'],['cots','PP'],['duyt','PP'],['daet','PP'],['love','PP'],['loev','PP'],['lvoe','PP'],
            ['leov','PP'],['eolv','PP'],['evol','PP'],['olve','PP']]
enc_in, dec_in, dec_out = encoding(easy_test)

In [23]:
pred = model.predict([np.array(enc_in),np.array(dec_in)])

1/1 [==============================] - 0s 37ms/step

In [24]:
for row,word in zip(pred.argmax(axis=-1).tolist(),easy_test) :
    print(word[0],"=>" ,''.join([alpha[c] for c in row if c not in (0,1,2)]))

clod => 감기
coko => 요리
donw => 아래
cots => 비용
duyt => 의무
daet => 날짜
love => 사랑
loev => 사랑
lvoe => 사랑
leov => 왼랑
eolv => 도다
evol => 매도
olve => 사랑

In [25]:
# Python
import pandas as pd
from prophet import Prophet

df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
display(df.tail()) # 날짜에 따른 y값 변동, 2007 ~ 2016

m = Prophet()
m.fit(df)
m # 예측 모델?

future = m.make_future_dataframe(periods=365) # 미래를 그려주는?
future.tail()

# forecast = m.predict(future)
# forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

# fig1 = m.plot(forecast)

Importing plotly failed. Interactive plots will not work.

              ds          y
2900  2016-01-16   7.817223
2901  2016-01-17   9.273878
2902  2016-01-18  10.333775
2903  2016-01-19   9.125871
2904  2016-01-20   8.891374

11:13:30 - cmdstanpy - INFO - Chain [1] start processing
11:13:31 - cmdstanpy - INFO - Chain [1] done processing

             ds
3265 2017-01-15
3266 2017-01-16
3267 2017-01-17
3268 2017-01-18
3269 2017-01-19